// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nagisa/internal/biz"
	"nagisa/internal/data/ent/nodeacl"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeAclCreate is the builder for creating a NodeAcl entity.
type NodeAclCreate struct {
	config
	mutation *NodeAclMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *NodeAclCreate) SetCreatedAt(v time.Time) *NodeAclCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableCreatedAt(v *time.Time) *NodeAclCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NodeAclCreate) SetUpdatedAt(v time.Time) *NodeAclCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableUpdatedAt(v *time.Time) *NodeAclCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *NodeAclCreate) SetNodeID(v uuid.UUID) *NodeAclCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableNodeID(v *uuid.UUID) *NodeAclCreate {
	if v != nil {
		_c.SetNodeID(*v)
	}
	return _c
}

// SetSubjectType sets the "subject_type" field.
func (_c *NodeAclCreate) SetSubjectType(v biz.SubjectType) *NodeAclCreate {
	_c.mutation.SetSubjectType(v)
	return _c
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableSubjectType(v *biz.SubjectType) *NodeAclCreate {
	if v != nil {
		_c.SetSubjectType(*v)
	}
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *NodeAclCreate) SetSubjectID(v string) *NodeAclCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableSubjectID(v *string) *NodeAclCreate {
	if v != nil {
		_c.SetSubjectID(*v)
	}
	return _c
}

// SetEffect sets the "effect" field.
func (_c *NodeAclCreate) SetEffect(v biz.Effect) *NodeAclCreate {
	_c.mutation.SetEffect(v)
	return _c
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableEffect(v *biz.Effect) *NodeAclCreate {
	if v != nil {
		_c.SetEffect(*v)
	}
	return _c
}

// SetPermissions sets the "permissions" field.
func (_c *NodeAclCreate) SetPermissions(v biz.PermMask) *NodeAclCreate {
	_c.mutation.SetPermissions(v)
	return _c
}

// SetNillablePermissions sets the "permissions" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillablePermissions(v *biz.PermMask) *NodeAclCreate {
	if v != nil {
		_c.SetPermissions(*v)
	}
	return _c
}

// SetInherit sets the "inherit" field.
func (_c *NodeAclCreate) SetInherit(v bool) *NodeAclCreate {
	_c.mutation.SetInherit(v)
	return _c
}

// SetNillableInherit sets the "inherit" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableInherit(v *bool) *NodeAclCreate {
	if v != nil {
		_c.SetInherit(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NodeAclCreate) SetCreatedBy(v uuid.UUID) *NodeAclCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableCreatedBy(v *uuid.UUID) *NodeAclCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NodeAclCreate) SetID(v uuid.UUID) *NodeAclCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NodeAclCreate) SetNillableID(v *uuid.UUID) *NodeAclCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NodeAclMutation object of the builder.
func (_c *NodeAclCreate) Mutation() *NodeAclMutation {
	return _c.mutation
}

// Save creates the NodeAcl in the database.
func (_c *NodeAclCreate) Save(ctx context.Context) (*NodeAcl, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeAclCreate) SaveX(ctx context.Context) *NodeAcl {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeAclCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeAclCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NodeAclCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := nodeacl.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := nodeacl.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		v := nodeacl.DefaultNodeID()
		_c.mutation.SetNodeID(v)
	}
	if _, ok := _c.mutation.SubjectType(); !ok {
		v := nodeacl.DefaultSubjectType
		_c.mutation.SetSubjectType(v)
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		v := nodeacl.DefaultSubjectID
		_c.mutation.SetSubjectID(v)
	}
	if _, ok := _c.mutation.Effect(); !ok {
		v := nodeacl.DefaultEffect
		_c.mutation.SetEffect(v)
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		v := nodeacl.DefaultPermissions
		_c.mutation.SetPermissions(v)
	}
	if _, ok := _c.mutation.Inherit(); !ok {
		v := nodeacl.DefaultInherit
		_c.mutation.SetInherit(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := nodeacl.DefaultCreatedBy()
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := nodeacl.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeAclCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NodeAcl.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NodeAcl.updated_at"`)}
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "NodeAcl.node_id"`)}
	}
	if _, ok := _c.mutation.SubjectType(); !ok {
		return &ValidationError{Name: "subject_type", err: errors.New(`ent: missing required field "NodeAcl.subject_type"`)}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "NodeAcl.subject_id"`)}
	}
	if _, ok := _c.mutation.Effect(); !ok {
		return &ValidationError{Name: "effect", err: errors.New(`ent: missing required field "NodeAcl.effect"`)}
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		return &ValidationError{Name: "permissions", err: errors.New(`ent: missing required field "NodeAcl.permissions"`)}
	}
	if _, ok := _c.mutation.Inherit(); !ok {
		return &ValidationError{Name: "inherit", err: errors.New(`ent: missing required field "NodeAcl.inherit"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "NodeAcl.created_by"`)}
	}
	return nil
}

func (_c *NodeAclCreate) sqlSave(ctx context.Context) (*NodeAcl, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeAclCreate) createSpec() (*NodeAcl, *sqlgraph.CreateSpec) {
	var (
		_node = &NodeAcl{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nodeacl.Table, sqlgraph.NewFieldSpec(nodeacl.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(nodeacl.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(nodeacl.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(nodeacl.FieldNodeID, field.TypeUUID, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.SubjectType(); ok {
		_spec.SetField(nodeacl.FieldSubjectType, field.TypeInt32, value)
		_node.SubjectType = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(nodeacl.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.Effect(); ok {
		_spec.SetField(nodeacl.FieldEffect, field.TypeInt32, value)
		_node.Effect = value
	}
	if value, ok := _c.mutation.Permissions(); ok {
		_spec.SetField(nodeacl.FieldPermissions, field.TypeInt64, value)
		_node.Permissions = value
	}
	if value, ok := _c.mutation.Inherit(); ok {
		_spec.SetField(nodeacl.FieldInherit, field.TypeBool, value)
		_node.Inherit = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(nodeacl.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// NodeAclCreateBulk is the builder for creating many NodeAcl entities in bulk.
type NodeAclCreateBulk struct {
	config
	err      error
	builders []*NodeAclCreate
}

// Save creates the NodeAcl entities in the database.
func (_c *NodeAclCreateBulk) Save(ctx context.Context) ([]*NodeAcl, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NodeAcl, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeAclMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeAclCreateBulk) SaveX(ctx context.Context) []*NodeAcl {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeAclCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeAclCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
