// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nagisa/internal/biz"
	"nagisa/internal/data/ent/node"
	"nagisa/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdate) SetUpdatedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *NodeUpdate) SetParentID(v uuid.UUID) *NodeUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableParentID(v *uuid.UUID) *NodeUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *NodeUpdate) SetName(v string) *NodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableName(v *string) *NodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameLower sets the "name_lower" field.
func (_u *NodeUpdate) SetNameLower(v string) *NodeUpdate {
	_u.mutation.SetNameLower(v)
	return _u
}

// SetNillableNameLower sets the "name_lower" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableNameLower(v *string) *NodeUpdate {
	if v != nil {
		_u.SetNameLower(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NodeUpdate) SetKind(v biz.NodeKind) *NodeUpdate {
	_u.mutation.ResetKind()
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableKind(v *biz.NodeKind) *NodeUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// AddKind adds value to the "kind" field.
func (_u *NodeUpdate) AddKind(v biz.NodeKind) *NodeUpdate {
	_u.mutation.AddKind(v)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *NodeUpdate) SetOwnerID(v uuid.UUID) *NodeUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableOwnerID(v *uuid.UUID) *NodeUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *NodeUpdate) SetSize(v int64) *NodeUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableSize(v *int64) *NodeUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *NodeUpdate) AddSize(v int64) *NodeUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *NodeUpdate) SetMimeType(v string) *NodeUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableMimeType(v *string) *NodeUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetExtension sets the "extension" field.
func (_u *NodeUpdate) SetExtension(v string) *NodeUpdate {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableExtension(v *string) *NodeUpdate {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// SetEtag sets the "etag" field.
func (_u *NodeUpdate) SetEtag(v string) *NodeUpdate {
	_u.mutation.SetEtag(v)
	return _u
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableEtag(v *string) *NodeUpdate {
	if v != nil {
		_u.SetEtag(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *NodeUpdate) SetStorageKey(v string) *NodeUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableStorageKey(v *string) *NodeUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdate) SetStatus(v biz.NodeStatus) *NodeUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableStatus(v *biz.NodeStatus) *NodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *NodeUpdate) AddStatus(v biz.NodeStatus) *NodeUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *NodeUpdate) SetDescription(v string) *NodeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableDescription(v *string) *NodeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *NodeUpdate) SetVisibility(v biz.Visibility) *NodeUpdate {
	_u.mutation.ResetVisibility()
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableVisibility(v *biz.Visibility) *NodeUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddVisibility adds value to the "visibility" field.
func (_u *NodeUpdate) AddVisibility(v biz.Visibility) *NodeUpdate {
	_u.mutation.AddVisibility(v)
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *NodeUpdate) SetPasswordHash(v string) *NodeUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePasswordHash(v *string) *NodeUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetPasswordHint sets the "password_hint" field.
func (_u *NodeUpdate) SetPasswordHint(v string) *NodeUpdate {
	_u.mutation.SetPasswordHint(v)
	return _u
}

// SetNillablePasswordHint sets the "password_hint" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePasswordHint(v *string) *NodeUpdate {
	if v != nil {
		_u.SetPasswordHint(*v)
	}
	return _u
}

// SetHasThumbnail sets the "has_thumbnail" field.
func (_u *NodeUpdate) SetHasThumbnail(v bool) *NodeUpdate {
	_u.mutation.SetHasThumbnail(v)
	return _u
}

// SetNillableHasThumbnail sets the "has_thumbnail" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableHasThumbnail(v *bool) *NodeUpdate {
	if v != nil {
		_u.SetHasThumbnail(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NodeUpdate) SetMetadata(v map[string]string) *NodeUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NodeUpdate) ClearMetadata() *NodeUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPath sets the "path" field.
func (_u *NodeUpdate) SetPath(v string) *NodeUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePath(v *string) *NodeUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *NodeUpdate) SetDepth(v int32) *NodeUpdate {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableDepth(v *int32) *NodeUpdate {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *NodeUpdate) AddDepth(v int32) *NodeUpdate {
	_u.mutation.AddDepth(v)
	return _u
}

// SetChildCount sets the "child_count" field.
func (_u *NodeUpdate) SetChildCount(v int64) *NodeUpdate {
	_u.mutation.ResetChildCount()
	_u.mutation.SetChildCount(v)
	return _u
}

// SetNillableChildCount sets the "child_count" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableChildCount(v *int64) *NodeUpdate {
	if v != nil {
		_u.SetChildCount(*v)
	}
	return _u
}

// AddChildCount adds value to the "child_count" field.
func (_u *NodeUpdate) AddChildCount(v int64) *NodeUpdate {
	_u.mutation.AddChildCount(v)
	return _u
}

// SetFileCount sets the "file_count" field.
func (_u *NodeUpdate) SetFileCount(v int64) *NodeUpdate {
	_u.mutation.ResetFileCount()
	_u.mutation.SetFileCount(v)
	return _u
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableFileCount(v *int64) *NodeUpdate {
	if v != nil {
		_u.SetFileCount(*v)
	}
	return _u
}

// AddFileCount adds value to the "file_count" field.
func (_u *NodeUpdate) AddFileCount(v int64) *NodeUpdate {
	_u.mutation.AddFileCount(v)
	return _u
}

// SetFolderCount sets the "folder_count" field.
func (_u *NodeUpdate) SetFolderCount(v int64) *NodeUpdate {
	_u.mutation.ResetFolderCount()
	_u.mutation.SetFolderCount(v)
	return _u
}

// SetNillableFolderCount sets the "folder_count" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableFolderCount(v *int64) *NodeUpdate {
	if v != nil {
		_u.SetFolderCount(*v)
	}
	return _u
}

// AddFolderCount adds value to the "folder_count" field.
func (_u *NodeUpdate) AddFolderCount(v int64) *NodeUpdate {
	_u.mutation.AddFolderCount(v)
	return _u
}

// SetSubtreeSize sets the "subtree_size" field.
func (_u *NodeUpdate) SetSubtreeSize(v int64) *NodeUpdate {
	_u.mutation.ResetSubtreeSize()
	_u.mutation.SetSubtreeSize(v)
	return _u
}

// SetNillableSubtreeSize sets the "subtree_size" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableSubtreeSize(v *int64) *NodeUpdate {
	if v != nil {
		_u.SetSubtreeSize(*v)
	}
	return _u
}

// AddSubtreeSize adds value to the "subtree_size" field.
func (_u *NodeUpdate) AddSubtreeSize(v int64) *NodeUpdate {
	_u.mutation.AddSubtreeSize(v)
	return _u
}

// SetCurrentVersionID sets the "current_version_id" field.
func (_u *NodeUpdate) SetCurrentVersionID(v uuid.UUID) *NodeUpdate {
	_u.mutation.SetCurrentVersionID(v)
	return _u
}

// SetNillableCurrentVersionID sets the "current_version_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCurrentVersionID(v *uuid.UUID) *NodeUpdate {
	if v != nil {
		_u.SetCurrentVersionID(*v)
	}
	return _u
}

// ClearCurrentVersionID clears the value of the "current_version_id" field.
func (_u *NodeUpdate) ClearCurrentVersionID() *NodeUpdate {
	_u.mutation.ClearCurrentVersionID()
	return _u
}

// SetVersionCount sets the "version_count" field.
func (_u *NodeUpdate) SetVersionCount(v int32) *NodeUpdate {
	_u.mutation.ResetVersionCount()
	_u.mutation.SetVersionCount(v)
	return _u
}

// SetNillableVersionCount sets the "version_count" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableVersionCount(v *int32) *NodeUpdate {
	if v != nil {
		_u.SetVersionCount(*v)
	}
	return _u
}

// AddVersionCount adds value to the "version_count" field.
func (_u *NodeUpdate) AddVersionCount(v int32) *NodeUpdate {
	_u.mutation.AddVersionCount(v)
	return _u
}

// SetTrashedAt sets the "trashed_at" field.
func (_u *NodeUpdate) SetTrashedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetTrashedAt(v)
	return _u
}

// SetNillableTrashedAt sets the "trashed_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableTrashedAt(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetTrashedAt(*v)
	}
	return _u
}

// ClearTrashedAt clears the value of the "trashed_at" field.
func (_u *NodeUpdate) ClearTrashedAt() *NodeUpdate {
	_u.mutation.ClearTrashedAt()
	return _u
}

// SetOriginalParentID sets the "original_parent_id" field.
func (_u *NodeUpdate) SetOriginalParentID(v uuid.UUID) *NodeUpdate {
	_u.mutation.SetOriginalParentID(v)
	return _u
}

// SetNillableOriginalParentID sets the "original_parent_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableOriginalParentID(v *uuid.UUID) *NodeUpdate {
	if v != nil {
		_u.SetOriginalParentID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NodeUpdate) SetCreatedBy(v uuid.UUID) *NodeUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCreatedBy(v *uuid.UUID) *NodeUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NodeUpdate) SetUpdatedBy(v uuid.UUID) *NodeUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableUpdatedBy(v *uuid.UUID) *NodeUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := node.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Node.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameLower(); ok {
		if err := node.NameLowerValidator(v); err != nil {
			return &ValidationError{Name: "name_lower", err: fmt.Errorf(`ent: validator failed for field "Node.name_lower": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(node.FieldParentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameLower(); ok {
		_spec.SetField(node.FieldNameLower, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(node.FieldKind, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedKind(); ok {
		_spec.AddField(node.FieldKind, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(node.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(node.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(node.FieldExtension, field.TypeString, value)
	}
	if value, ok := _u.mutation.Etag(); ok {
		_spec.SetField(node.FieldEtag, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(node.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(node.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(node.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(node.FieldVisibility, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVisibility(); ok {
		_spec.AddField(node.FieldVisibility, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(node.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHint(); ok {
		_spec.SetField(node.FieldPasswordHint, field.TypeString, value)
	}
	if value, ok := _u.mutation.HasThumbnail(); ok {
		_spec.SetField(node.FieldHasThumbnail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(node.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(node.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(node.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(node.FieldDepth, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(node.FieldDepth, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ChildCount(); ok {
		_spec.SetField(node.FieldChildCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChildCount(); ok {
		_spec.AddField(node.FieldChildCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileCount(); ok {
		_spec.SetField(node.FieldFileCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileCount(); ok {
		_spec.AddField(node.FieldFileCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FolderCount(); ok {
		_spec.SetField(node.FieldFolderCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFolderCount(); ok {
		_spec.AddField(node.FieldFolderCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubtreeSize(); ok {
		_spec.SetField(node.FieldSubtreeSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubtreeSize(); ok {
		_spec.AddField(node.FieldSubtreeSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CurrentVersionID(); ok {
		_spec.SetField(node.FieldCurrentVersionID, field.TypeUUID, value)
	}
	if _u.mutation.CurrentVersionIDCleared() {
		_spec.ClearField(node.FieldCurrentVersionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.VersionCount(); ok {
		_spec.SetField(node.FieldVersionCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersionCount(); ok {
		_spec.AddField(node.FieldVersionCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TrashedAt(); ok {
		_spec.SetField(node.FieldTrashedAt, field.TypeTime, value)
	}
	if _u.mutation.TrashedAtCleared() {
		_spec.ClearField(node.FieldTrashedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OriginalParentID(); ok {
		_spec.SetField(node.FieldOriginalParentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(node.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(node.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdateOne) SetUpdatedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *NodeUpdateOne) SetParentID(v uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableParentID(v *uuid.UUID) *NodeUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *NodeUpdateOne) SetName(v string) *NodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableName(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameLower sets the "name_lower" field.
func (_u *NodeUpdateOne) SetNameLower(v string) *NodeUpdateOne {
	_u.mutation.SetNameLower(v)
	return _u
}

// SetNillableNameLower sets the "name_lower" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableNameLower(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetNameLower(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NodeUpdateOne) SetKind(v biz.NodeKind) *NodeUpdateOne {
	_u.mutation.ResetKind()
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableKind(v *biz.NodeKind) *NodeUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// AddKind adds value to the "kind" field.
func (_u *NodeUpdateOne) AddKind(v biz.NodeKind) *NodeUpdateOne {
	_u.mutation.AddKind(v)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *NodeUpdateOne) SetOwnerID(v uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableOwnerID(v *uuid.UUID) *NodeUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *NodeUpdateOne) SetSize(v int64) *NodeUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableSize(v *int64) *NodeUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *NodeUpdateOne) AddSize(v int64) *NodeUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *NodeUpdateOne) SetMimeType(v string) *NodeUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableMimeType(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetExtension sets the "extension" field.
func (_u *NodeUpdateOne) SetExtension(v string) *NodeUpdateOne {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableExtension(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// SetEtag sets the "etag" field.
func (_u *NodeUpdateOne) SetEtag(v string) *NodeUpdateOne {
	_u.mutation.SetEtag(v)
	return _u
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableEtag(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetEtag(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *NodeUpdateOne) SetStorageKey(v string) *NodeUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableStorageKey(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdateOne) SetStatus(v biz.NodeStatus) *NodeUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableStatus(v *biz.NodeStatus) *NodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *NodeUpdateOne) AddStatus(v biz.NodeStatus) *NodeUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *NodeUpdateOne) SetDescription(v string) *NodeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableDescription(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *NodeUpdateOne) SetVisibility(v biz.Visibility) *NodeUpdateOne {
	_u.mutation.ResetVisibility()
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableVisibility(v *biz.Visibility) *NodeUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddVisibility adds value to the "visibility" field.
func (_u *NodeUpdateOne) AddVisibility(v biz.Visibility) *NodeUpdateOne {
	_u.mutation.AddVisibility(v)
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *NodeUpdateOne) SetPasswordHash(v string) *NodeUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePasswordHash(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetPasswordHint sets the "password_hint" field.
func (_u *NodeUpdateOne) SetPasswordHint(v string) *NodeUpdateOne {
	_u.mutation.SetPasswordHint(v)
	return _u
}

// SetNillablePasswordHint sets the "password_hint" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePasswordHint(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetPasswordHint(*v)
	}
	return _u
}

// SetHasThumbnail sets the "has_thumbnail" field.
func (_u *NodeUpdateOne) SetHasThumbnail(v bool) *NodeUpdateOne {
	_u.mutation.SetHasThumbnail(v)
	return _u
}

// SetNillableHasThumbnail sets the "has_thumbnail" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableHasThumbnail(v *bool) *NodeUpdateOne {
	if v != nil {
		_u.SetHasThumbnail(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NodeUpdateOne) SetMetadata(v map[string]string) *NodeUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NodeUpdateOne) ClearMetadata() *NodeUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPath sets the "path" field.
func (_u *NodeUpdateOne) SetPath(v string) *NodeUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePath(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *NodeUpdateOne) SetDepth(v int32) *NodeUpdateOne {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableDepth(v *int32) *NodeUpdateOne {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *NodeUpdateOne) AddDepth(v int32) *NodeUpdateOne {
	_u.mutation.AddDepth(v)
	return _u
}

// SetChildCount sets the "child_count" field.
func (_u *NodeUpdateOne) SetChildCount(v int64) *NodeUpdateOne {
	_u.mutation.ResetChildCount()
	_u.mutation.SetChildCount(v)
	return _u
}

// SetNillableChildCount sets the "child_count" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableChildCount(v *int64) *NodeUpdateOne {
	if v != nil {
		_u.SetChildCount(*v)
	}
	return _u
}

// AddChildCount adds value to the "child_count" field.
func (_u *NodeUpdateOne) AddChildCount(v int64) *NodeUpdateOne {
	_u.mutation.AddChildCount(v)
	return _u
}

// SetFileCount sets the "file_count" field.
func (_u *NodeUpdateOne) SetFileCount(v int64) *NodeUpdateOne {
	_u.mutation.ResetFileCount()
	_u.mutation.SetFileCount(v)
	return _u
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableFileCount(v *int64) *NodeUpdateOne {
	if v != nil {
		_u.SetFileCount(*v)
	}
	return _u
}

// AddFileCount adds value to the "file_count" field.
func (_u *NodeUpdateOne) AddFileCount(v int64) *NodeUpdateOne {
	_u.mutation.AddFileCount(v)
	return _u
}

// SetFolderCount sets the "folder_count" field.
func (_u *NodeUpdateOne) SetFolderCount(v int64) *NodeUpdateOne {
	_u.mutation.ResetFolderCount()
	_u.mutation.SetFolderCount(v)
	return _u
}

// SetNillableFolderCount sets the "folder_count" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableFolderCount(v *int64) *NodeUpdateOne {
	if v != nil {
		_u.SetFolderCount(*v)
	}
	return _u
}

// AddFolderCount adds value to the "folder_count" field.
func (_u *NodeUpdateOne) AddFolderCount(v int64) *NodeUpdateOne {
	_u.mutation.AddFolderCount(v)
	return _u
}

// SetSubtreeSize sets the "subtree_size" field.
func (_u *NodeUpdateOne) SetSubtreeSize(v int64) *NodeUpdateOne {
	_u.mutation.ResetSubtreeSize()
	_u.mutation.SetSubtreeSize(v)
	return _u
}

// SetNillableSubtreeSize sets the "subtree_size" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableSubtreeSize(v *int64) *NodeUpdateOne {
	if v != nil {
		_u.SetSubtreeSize(*v)
	}
	return _u
}

// AddSubtreeSize adds value to the "subtree_size" field.
func (_u *NodeUpdateOne) AddSubtreeSize(v int64) *NodeUpdateOne {
	_u.mutation.AddSubtreeSize(v)
	return _u
}

// SetCurrentVersionID sets the "current_version_id" field.
func (_u *NodeUpdateOne) SetCurrentVersionID(v uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetCurrentVersionID(v)
	return _u
}

// SetNillableCurrentVersionID sets the "current_version_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCurrentVersionID(v *uuid.UUID) *NodeUpdateOne {
	if v != nil {
		_u.SetCurrentVersionID(*v)
	}
	return _u
}

// ClearCurrentVersionID clears the value of the "current_version_id" field.
func (_u *NodeUpdateOne) ClearCurrentVersionID() *NodeUpdateOne {
	_u.mutation.ClearCurrentVersionID()
	return _u
}

// SetVersionCount sets the "version_count" field.
func (_u *NodeUpdateOne) SetVersionCount(v int32) *NodeUpdateOne {
	_u.mutation.ResetVersionCount()
	_u.mutation.SetVersionCount(v)
	return _u
}

// SetNillableVersionCount sets the "version_count" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableVersionCount(v *int32) *NodeUpdateOne {
	if v != nil {
		_u.SetVersionCount(*v)
	}
	return _u
}

// AddVersionCount adds value to the "version_count" field.
func (_u *NodeUpdateOne) AddVersionCount(v int32) *NodeUpdateOne {
	_u.mutation.AddVersionCount(v)
	return _u
}

// SetTrashedAt sets the "trashed_at" field.
func (_u *NodeUpdateOne) SetTrashedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetTrashedAt(v)
	return _u
}

// SetNillableTrashedAt sets the "trashed_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableTrashedAt(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetTrashedAt(*v)
	}
	return _u
}

// ClearTrashedAt clears the value of the "trashed_at" field.
func (_u *NodeUpdateOne) ClearTrashedAt() *NodeUpdateOne {
	_u.mutation.ClearTrashedAt()
	return _u
}

// SetOriginalParentID sets the "original_parent_id" field.
func (_u *NodeUpdateOne) SetOriginalParentID(v uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetOriginalParentID(v)
	return _u
}

// SetNillableOriginalParentID sets the "original_parent_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableOriginalParentID(v *uuid.UUID) *NodeUpdateOne {
	if v != nil {
		_u.SetOriginalParentID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NodeUpdateOne) SetCreatedBy(v uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *NodeUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NodeUpdateOne) SetUpdatedBy(v uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *NodeUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := node.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Node.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameLower(); ok {
		if err := node.NameLowerValidator(v); err != nil {
			return &ValidationError{Name: "name_lower", err: fmt.Errorf(`ent: validator failed for field "Node.name_lower": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(node.FieldParentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameLower(); ok {
		_spec.SetField(node.FieldNameLower, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(node.FieldKind, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedKind(); ok {
		_spec.AddField(node.FieldKind, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(node.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(node.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(node.FieldExtension, field.TypeString, value)
	}
	if value, ok := _u.mutation.Etag(); ok {
		_spec.SetField(node.FieldEtag, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(node.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(node.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(node.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(node.FieldVisibility, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVisibility(); ok {
		_spec.AddField(node.FieldVisibility, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(node.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHint(); ok {
		_spec.SetField(node.FieldPasswordHint, field.TypeString, value)
	}
	if value, ok := _u.mutation.HasThumbnail(); ok {
		_spec.SetField(node.FieldHasThumbnail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(node.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(node.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(node.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(node.FieldDepth, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(node.FieldDepth, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ChildCount(); ok {
		_spec.SetField(node.FieldChildCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChildCount(); ok {
		_spec.AddField(node.FieldChildCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileCount(); ok {
		_spec.SetField(node.FieldFileCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileCount(); ok {
		_spec.AddField(node.FieldFileCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FolderCount(); ok {
		_spec.SetField(node.FieldFolderCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFolderCount(); ok {
		_spec.AddField(node.FieldFolderCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubtreeSize(); ok {
		_spec.SetField(node.FieldSubtreeSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubtreeSize(); ok {
		_spec.AddField(node.FieldSubtreeSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CurrentVersionID(); ok {
		_spec.SetField(node.FieldCurrentVersionID, field.TypeUUID, value)
	}
	if _u.mutation.CurrentVersionIDCleared() {
		_spec.ClearField(node.FieldCurrentVersionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.VersionCount(); ok {
		_spec.SetField(node.FieldVersionCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersionCount(); ok {
		_spec.AddField(node.FieldVersionCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TrashedAt(); ok {
		_spec.SetField(node.FieldTrashedAt, field.TypeTime, value)
	}
	if _u.mutation.TrashedAtCleared() {
		_spec.ClearField(node.FieldTrashedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OriginalParentID(); ok {
		_spec.SetField(node.FieldOriginalParentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(node.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(node.FieldUpdatedBy, field.TypeUUID, value)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
