// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nagisa/internal/data/ent/uploadpart"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UploadPartCreate is the builder for creating a UploadPart entity.
type UploadPartCreate struct {
	config
	mutation *UploadPartMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UploadPartCreate) SetCreatedAt(v time.Time) *UploadPartCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableCreatedAt(v *time.Time) *UploadPartCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UploadPartCreate) SetUpdatedAt(v time.Time) *UploadPartCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableUpdatedAt(v *time.Time) *UploadPartCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUploadID sets the "upload_id" field.
func (_c *UploadPartCreate) SetUploadID(v uuid.UUID) *UploadPartCreate {
	_c.mutation.SetUploadID(v)
	return _c
}

// SetNillableUploadID sets the "upload_id" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableUploadID(v *uuid.UUID) *UploadPartCreate {
	if v != nil {
		_c.SetUploadID(*v)
	}
	return _c
}

// SetPartNumber sets the "part_number" field.
func (_c *UploadPartCreate) SetPartNumber(v int32) *UploadPartCreate {
	_c.mutation.SetPartNumber(v)
	return _c
}

// SetNillablePartNumber sets the "part_number" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillablePartNumber(v *int32) *UploadPartCreate {
	if v != nil {
		_c.SetPartNumber(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *UploadPartCreate) SetSize(v int64) *UploadPartCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableSize(v *int64) *UploadPartCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetEtag sets the "etag" field.
func (_c *UploadPartCreate) SetEtag(v string) *UploadPartCreate {
	_c.mutation.SetEtag(v)
	return _c
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableEtag(v *string) *UploadPartCreate {
	if v != nil {
		_c.SetEtag(*v)
	}
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *UploadPartCreate) SetStorageKey(v string) *UploadPartCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableStorageKey(v *string) *UploadPartCreate {
	if v != nil {
		_c.SetStorageKey(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UploadPartCreate) SetID(v uuid.UUID) *UploadPartCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableID(v *uuid.UUID) *UploadPartCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UploadPartMutation object of the builder.
func (_c *UploadPartCreate) Mutation() *UploadPartMutation {
	return _c.mutation
}

// Save creates the UploadPart in the database.
func (_c *UploadPartCreate) Save(ctx context.Context) (*UploadPart, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UploadPartCreate) SaveX(ctx context.Context) *UploadPart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadPartCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadPartCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UploadPartCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uploadpart.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := uploadpart.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UploadID(); !ok {
		v := uploadpart.DefaultUploadID()
		_c.mutation.SetUploadID(v)
	}
	if _, ok := _c.mutation.PartNumber(); !ok {
		v := uploadpart.DefaultPartNumber
		_c.mutation.SetPartNumber(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := uploadpart.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Etag(); !ok {
		v := uploadpart.DefaultEtag
		_c.mutation.SetEtag(v)
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		v := uploadpart.DefaultStorageKey
		_c.mutation.SetStorageKey(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := uploadpart.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UploadPartCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UploadPart.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UploadPart.updated_at"`)}
	}
	if _, ok := _c.mutation.UploadID(); !ok {
		return &ValidationError{Name: "upload_id", err: errors.New(`ent: missing required field "UploadPart.upload_id"`)}
	}
	if _, ok := _c.mutation.PartNumber(); !ok {
		return &ValidationError{Name: "part_number", err: errors.New(`ent: missing required field "UploadPart.part_number"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "UploadPart.size"`)}
	}
	if _, ok := _c.mutation.Etag(); !ok {
		return &ValidationError{Name: "etag", err: errors.New(`ent: missing required field "UploadPart.etag"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "UploadPart.storage_key"`)}
	}
	return nil
}

func (_c *UploadPartCreate) sqlSave(ctx context.Context) (*UploadPart, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UploadPartCreate) createSpec() (*UploadPart, *sqlgraph.CreateSpec) {
	var (
		_node = &UploadPart{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uploadpart.Table, sqlgraph.NewFieldSpec(uploadpart.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uploadpart.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadpart.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UploadID(); ok {
		_spec.SetField(uploadpart.FieldUploadID, field.TypeUUID, value)
		_node.UploadID = value
	}
	if value, ok := _c.mutation.PartNumber(); ok {
		_spec.SetField(uploadpart.FieldPartNumber, field.TypeInt32, value)
		_node.PartNumber = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(uploadpart.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Etag(); ok {
		_spec.SetField(uploadpart.FieldEtag, field.TypeString, value)
		_node.Etag = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(uploadpart.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	return _node, _spec
}

// UploadPartCreateBulk is the builder for creating many UploadPart entities in bulk.
type UploadPartCreateBulk struct {
	config
	err      error
	builders []*UploadPartCreate
}

// Save creates the UploadPart entities in the database.
func (_c *UploadPartCreateBulk) Save(ctx context.Context) ([]*UploadPart, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UploadPart, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UploadPartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UploadPartCreateBulk) SaveX(ctx context.Context) []*UploadPart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadPartCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadPartCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
