// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: netdisk/v1/audit.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditLog is one recorded action.
type AuditLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Account that performed the action. Empty for anonymous callers.
	ActorId string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Account name at the time of the action.
	ActorName string `protobuf:"bytes,3,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	// Machine readable action name, for example "node.create_folder".
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// Human readable Chinese description.
	ActionDisplay string `protobuf:"bytes,5,opt,name=action_display,json=actionDisplay,proto3" json:"action_display,omitempty"`
	// Resource family, for example "node", "user" or "share".
	TargetType string `protobuf:"bytes,6,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// Identifier of the affected resource.
	TargetId string `protobuf:"bytes,7,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Display name of the affected resource at the time of the action.
	TargetName string `protobuf:"bytes,8,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	// Whether the action succeeded.
	Success bool `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	// Error reason when success is false.
	ErrorReason string `protobuf:"bytes,10,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	// Free-form detail, for example the previous and new name.
	Detail map[string]string `protobuf:"bytes,11,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Source address.
	Ip string `protobuf:"bytes,12,opt,name=ip,proto3" json:"ip,omitempty"`
	// Client user agent.
	UserAgent string `protobuf:"bytes,13,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Correlation id shared with the server logs.
	RequestId string `protobuf:"bytes,14,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Time the action completed.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditLog) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetActionDisplay() string {
	if x != nil {
		return x.ActionDisplay
	}
	return ""
}

func (x *AuditLog) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditLog) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditLog) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *AuditLog) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuditLog) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *AuditLog) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *AuditLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLog) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// AuditLogSet is a paginated collection of audit entries.
type AuditLogSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogSet) Reset() {
	*x = AuditLogSet{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogSet) ProtoMessage() {}

func (x *AuditLogSet) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogSet.ProtoReflect.Descriptor instead.
func (*AuditLogSet) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditLogSet) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AuditLogSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *AuditLogSet) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// AuditActionCount is one entry of an aggregated audit summary.
type AuditActionCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ActionDisplay string                 `protobuf:"bytes,2,opt,name=action_display,json=actionDisplay,proto3" json:"action_display,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditActionCount) Reset() {
	*x = AuditActionCount{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditActionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditActionCount) ProtoMessage() {}

func (x *AuditActionCount) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditActionCount.ProtoReflect.Descriptor instead.
func (*AuditActionCount) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditActionCount) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditActionCount) GetActionDisplay() string {
	if x != nil {
		return x.ActionDisplay
	}
	return ""
}

func (x *AuditActionCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// AuditActorCount is one actor of an aggregated audit summary.
type AuditActorCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorName     string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditActorCount) Reset() {
	*x = AuditActorCount{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditActorCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditActorCount) ProtoMessage() {}

func (x *AuditActorCount) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditActorCount.ProtoReflect.Descriptor instead.
func (*AuditActorCount) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditActorCount) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditActorCount) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *AuditActorCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// AuditSummary aggregates the audit trail over a time window.
type AuditSummary struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	From         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Total        int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	FailureCount int64                  `protobuf:"varint,4,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	ByAction     []*AuditActionCount    `protobuf:"bytes,5,rep,name=by_action,json=byAction,proto3" json:"by_action,omitempty"`
	ByActor      []*AuditActorCount     `protobuf:"bytes,6,rep,name=by_actor,json=byActor,proto3" json:"by_actor,omitempty"`
	// Counts keyed by ISO-8601 date.
	ByDay         map[string]int64 `protobuf:"bytes,7,rep,name=by_day,json=byDay,proto3" json:"by_day,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditSummary) Reset() {
	*x = AuditSummary{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditSummary) ProtoMessage() {}

func (x *AuditSummary) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditSummary.ProtoReflect.Descriptor instead.
func (*AuditSummary) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *AuditSummary) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *AuditSummary) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *AuditSummary) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AuditSummary) GetFailureCount() int64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *AuditSummary) GetByAction() []*AuditActionCount {
	if x != nil {
		return x.ByAction
	}
	return nil
}

func (x *AuditSummary) GetByActor() []*AuditActorCount {
	if x != nil {
		return x.ByActor
	}
	return nil
}

func (x *AuditSummary) GetByDay() map[string]int64 {
	if x != nil {
		return x.ByDay
	}
	return nil
}

// ListAuditLogsRequest is the input for AuditService.ListAuditLogs.
type ListAuditLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Maximum number of entries to return. Defaults to 20, capped at
	// 500.
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. The standard list filter.
	// Supported fields:
	//   - `actor_id`
	//   - `actor_name`
	//   - `action` (i.e. `action:"node."` for a prefix match)
	//   - `target_type`
	//   - `target_id`
	//   - `success` (i.e. `success` for successful calls, `NOT success` for
	//     failed ones; `success=true` and `success=false` are also accepted)
	//   - `ip`
	//   - `created_at` range
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Comma-separated ordering fields, in the AIP syntax where a
	// descending field is written with a `desc` suffix (`order_by=created_at desc`).
	// Supported fields: `created_at`, `action`, `actor_name`.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{5}
}

func (x *ListAuditLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditLogsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditLogsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAuditLogsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// GetAuditLogRequest is the input for AuditService.GetAuditLog.
type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuditLogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetAuditSummaryRequest is the input for AuditService.GetAuditSummary.
type GetAuditSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Start of the window. Defaults to 7 days before to.
	From *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Optional. End of the window. Defaults to now.
	To *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Optional. Restrict the aggregation to one action prefix.
	ActionPrefix  string `protobuf:"bytes,3,opt,name=action_prefix,json=actionPrefix,proto3" json:"action_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditSummaryRequest) Reset() {
	*x = GetAuditSummaryRequest{}
	mi := &file_netdisk_v1_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditSummaryRequest) ProtoMessage() {}

func (x *GetAuditSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAuditSummaryRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_audit_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuditSummaryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetAuditSummaryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetAuditSummaryRequest) GetActionPrefix() string {
	if x != nil {
		return x.ActionPrefix
	}
	return ""
}

var File_netdisk_v1_audit_proto protoreflect.FileDescriptor

const file_netdisk_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x16netdisk/v1/audit.proto\x12\n" +
	"netdisk.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x04\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x03 \x01(\tR\tactorName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12%\n" +
	"\x0eaction_display\x18\x05 \x01(\tR\ractionDisplay\x12\x1f\n" +
	"\vtarget_type\x18\x06 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\a \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\b \x01(\tR\n" +
	"targetName\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12!\n" +
	"\ferror_reason\x18\n" +
	" \x01(\tR\verrorReason\x128\n" +
	"\x06detail\x18\v \x03(\v2 .netdisk.v1.AuditLog.DetailEntryR\x06detail\x12\x0e\n" +
	"\x02ip\x18\f \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\r \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x0e \x01(\tR\trequestId\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\vAuditLogSet\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.netdisk.v1.AuditLogR\x04logs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\"g\n" +
	"\x10AuditActionCount\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12%\n" +
	"\x0eaction_display\x18\x02 \x01(\tR\ractionDisplay\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"a\n" +
	"\x0fAuditActorCount\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"\x8e\x03\n" +
	"\fAuditSummary\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12#\n" +
	"\rfailure_count\x18\x04 \x01(\x03R\ffailureCount\x129\n" +
	"\tby_action\x18\x05 \x03(\v2\x1c.netdisk.v1.AuditActionCountR\bbyAction\x126\n" +
	"\bby_actor\x18\x06 \x03(\v2\x1b.netdisk.v1.AuditActorCountR\abyActor\x12:\n" +
	"\x06by_day\x18\a \x03(\v2#.netdisk.v1.AuditSummary.ByDayEntryR\x05byDay\x1a8\n" +
	"\n" +
	"ByDayEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x85\x01\n" +
	"\x14ListAuditLogsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\")\n" +
	"\x12GetAuditLogRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x99\x01\n" +
	"\x16GetAuditSummaryRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12#\n" +
	"\raction_prefix\x18\x03 \x01(\tR\factionPrefix2\xc5\x02\n" +
	"\fAuditService\x12g\n" +
	"\rListAuditLogs\x12 .netdisk.v1.ListAuditLogsRequest\x1a\x17.netdisk.v1.AuditLogSet\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/audit/logs/list\x12`\n" +
	"\vGetAuditLog\x12\x1e.netdisk.v1.GetAuditLogRequest\x1a\x14.netdisk.v1.AuditLog\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/audit/logs/{id}\x12j\n" +
	"\x0fGetAuditSummary\x12\".netdisk.v1.GetAuditSummaryRequest\x1a\x18.netdisk.v1.AuditSummary\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/audit/summaryBM\n" +
	"\x14io.nagisa.netdisk.v1B\n" +
	"AuditProtoP\x01Z\x18nagisa/api/netdisk/v1;v1\xa2\x02\fAPINetdiskV1b\x06proto3"

var (
	file_netdisk_v1_audit_proto_rawDescOnce sync.Once
	file_netdisk_v1_audit_proto_rawDescData []byte
)

func file_netdisk_v1_audit_proto_rawDescGZIP() []byte {
	file_netdisk_v1_audit_proto_rawDescOnce.Do(func() {
		file_netdisk_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_netdisk_v1_audit_proto_rawDesc), len(file_netdisk_v1_audit_proto_rawDesc)))
	})
	return file_netdisk_v1_audit_proto_rawDescData
}

var file_netdisk_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_netdisk_v1_audit_proto_goTypes = []any{
	(*AuditLog)(nil),               // 0: netdisk.v1.AuditLog
	(*AuditLogSet)(nil),            // 1: netdisk.v1.AuditLogSet
	(*AuditActionCount)(nil),       // 2: netdisk.v1.AuditActionCount
	(*AuditActorCount)(nil),        // 3: netdisk.v1.AuditActorCount
	(*AuditSummary)(nil),           // 4: netdisk.v1.AuditSummary
	(*ListAuditLogsRequest)(nil),   // 5: netdisk.v1.ListAuditLogsRequest
	(*GetAuditLogRequest)(nil),     // 6: netdisk.v1.GetAuditLogRequest
	(*GetAuditSummaryRequest)(nil), // 7: netdisk.v1.GetAuditSummaryRequest
	nil,                            // 8: netdisk.v1.AuditLog.DetailEntry
	nil,                            // 9: netdisk.v1.AuditSummary.ByDayEntry
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_netdisk_v1_audit_proto_depIdxs = []int32{
	8,  // 0: netdisk.v1.AuditLog.detail:type_name -> netdisk.v1.AuditLog.DetailEntry
	10, // 1: netdisk.v1.AuditLog.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: netdisk.v1.AuditLogSet.logs:type_name -> netdisk.v1.AuditLog
	10, // 3: netdisk.v1.AuditSummary.from:type_name -> google.protobuf.Timestamp
	10, // 4: netdisk.v1.AuditSummary.to:type_name -> google.protobuf.Timestamp
	2,  // 5: netdisk.v1.AuditSummary.by_action:type_name -> netdisk.v1.AuditActionCount
	3,  // 6: netdisk.v1.AuditSummary.by_actor:type_name -> netdisk.v1.AuditActorCount
	9,  // 7: netdisk.v1.AuditSummary.by_day:type_name -> netdisk.v1.AuditSummary.ByDayEntry
	10, // 8: netdisk.v1.GetAuditSummaryRequest.from:type_name -> google.protobuf.Timestamp
	10, // 9: netdisk.v1.GetAuditSummaryRequest.to:type_name -> google.protobuf.Timestamp
	5,  // 10: netdisk.v1.AuditService.ListAuditLogs:input_type -> netdisk.v1.ListAuditLogsRequest
	6,  // 11: netdisk.v1.AuditService.GetAuditLog:input_type -> netdisk.v1.GetAuditLogRequest
	7,  // 12: netdisk.v1.AuditService.GetAuditSummary:input_type -> netdisk.v1.GetAuditSummaryRequest
	1,  // 13: netdisk.v1.AuditService.ListAuditLogs:output_type -> netdisk.v1.AuditLogSet
	0,  // 14: netdisk.v1.AuditService.GetAuditLog:output_type -> netdisk.v1.AuditLog
	4,  // 15: netdisk.v1.AuditService.GetAuditSummary:output_type -> netdisk.v1.AuditSummary
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_netdisk_v1_audit_proto_init() }
func file_netdisk_v1_audit_proto_init() {
	if File_netdisk_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_netdisk_v1_audit_proto_rawDesc), len(file_netdisk_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_netdisk_v1_audit_proto_goTypes,
		DependencyIndexes: file_netdisk_v1_audit_proto_depIdxs,
		MessageInfos:      file_netdisk_v1_audit_proto_msgTypes,
	}.Build()
	File_netdisk_v1_audit_proto = out.File
	file_netdisk_v1_audit_proto_goTypes = nil
	file_netdisk_v1_audit_proto_depIdxs = nil
}
