// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: netdisk/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthConfig is the public pre-login parameter set.
type AuthConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the password key, echoed by clients so a key rotation can be
	// detected without a failed login.
	PasswordKeyId string `protobuf:"bytes,1,opt,name=password_key_id,json=passwordKeyId,proto3" json:"password_key_id,omitempty"`
	// Encoding the client must apply to every password field, currently
	// "rsa-oaep-sha256".
	PasswordEncoding string `protobuf:"bytes,2,opt,name=password_encoding,json=passwordEncoding,proto3" json:"password_encoding,omitempty"`
	// PEM encoded PKCS#8 RSA public key.
	PasswordPublicKey string `protobuf:"bytes,3,opt,name=password_public_key,json=passwordPublicKey,proto3" json:"password_public_key,omitempty"`
	// Access token lifetime in seconds.
	AccessTokenTtlSeconds int32 `protobuf:"varint,4,opt,name=access_token_ttl_seconds,json=accessTokenTtlSeconds,proto3" json:"access_token_ttl_seconds,omitempty"`
	// Refresh token lifetime in seconds.
	RefreshTokenTtlSeconds int32 `protobuf:"varint,5,opt,name=refresh_token_ttl_seconds,json=refreshTokenTtlSeconds,proto3" json:"refresh_token_ttl_seconds,omitempty"`
	// Whether the deployment accepts an unencoded password. Only ever true in a
	// local development configuration.
	PlainPasswordAllowed bool `protobuf:"varint,6,opt,name=plain_password_allowed,json=plainPasswordAllowed,proto3" json:"plain_password_allowed,omitempty"`
	// Server clock at the time of the response.
	ServerTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Whether the deployment hands out a read-only guest session without a
	// password through AuthService.GuestLogin.
	GuestLoginEnabled bool `protobuf:"varint,8,opt,name=guest_login_enabled,json=guestLoginEnabled,proto3" json:"guest_login_enabled,omitempty"`
	// Minimum number of characters accepted in a password field. Account,
	// folder and share passwords share this policy, so a client can reject a
	// too short value before submitting it.
	MinPasswordLength int32 `protobuf:"varint,9,opt,name=min_password_length,json=minPasswordLength,proto3" json:"min_password_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthConfig) GetPasswordKeyId() string {
	if x != nil {
		return x.PasswordKeyId
	}
	return ""
}

func (x *AuthConfig) GetPasswordEncoding() string {
	if x != nil {
		return x.PasswordEncoding
	}
	return ""
}

func (x *AuthConfig) GetPasswordPublicKey() string {
	if x != nil {
		return x.PasswordPublicKey
	}
	return ""
}

func (x *AuthConfig) GetAccessTokenTtlSeconds() int32 {
	if x != nil {
		return x.AccessTokenTtlSeconds
	}
	return 0
}

func (x *AuthConfig) GetRefreshTokenTtlSeconds() int32 {
	if x != nil {
		return x.RefreshTokenTtlSeconds
	}
	return 0
}

func (x *AuthConfig) GetPlainPasswordAllowed() bool {
	if x != nil {
		return x.PlainPasswordAllowed
	}
	return false
}

func (x *AuthConfig) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *AuthConfig) GetGuestLoginEnabled() bool {
	if x != nil {
		return x.GuestLoginEnabled
	}
	return false
}

func (x *AuthConfig) GetMinPasswordLength() int32 {
	if x != nil {
		return x.MinPasswordLength
	}
	return 0
}

// Session is one refresh token family shown to its owner.
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Client address that created the session.
	Ip string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	// User agent recorded at creation time.
	UserAgent string `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Time at which the session was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Time at which the session was last refreshed.
	LastUsedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	// Time at which the session expires.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Whether the session is still usable.
	Active bool `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	// Whether this is the session behind the current request.
	Current       bool `protobuf:"varint,8,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Session) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Session) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

// SessionSet is a page of sessions.
type SessionSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSet) Reset() {
	*x = SessionSet{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSet) ProtoMessage() {}

func (x *SessionSet) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSet.ProtoReflect.Descriptor instead.
func (*SessionSet) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SessionSet) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SessionSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetAuthConfigRequest is the input for AuthService.GetAuthConfig.
type GetAuthConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthConfigRequest) Reset() {
	*x = GetAuthConfigRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthConfigRequest) ProtoMessage() {}

func (x *GetAuthConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAuthConfigRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{3}
}

// LoginRequest is the input for AuthService.Login.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account name.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// RSA-OAEP(SHA-256) encrypted, base64 encoded password.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Client address hint used when the request does not come through a proxy.
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// Client user agent hint.
	UserAgent string `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Whether the refresh token should be long lived.
	RememberMe    bool `protobuf:"varint,5,opt,name=remember_me,json=rememberMe,proto3" json:"remember_me,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LoginRequest) GetRememberMe() bool {
	if x != nil {
		return x.RememberMe
	}
	return false
}

// GuestLoginRequest is the input for AuthService.GuestLogin.
type GuestLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client address hint used when the request does not come through a proxy.
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Client user agent hint.
	UserAgent     string `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestLoginRequest) Reset() {
	*x = GuestLoginRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestLoginRequest) ProtoMessage() {}

func (x *GuestLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestLoginRequest.ProtoReflect.Descriptor instead.
func (*GuestLoginRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GuestLoginRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GuestLoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// LoginReply carries the token pair and the authenticated account.
type LoginReply struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AccessToken  string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType    string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// Access token lifetime in seconds.
	ExpiresIn int32 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Refresh token lifetime in seconds.
	RefreshExpiresIn int32 `protobuf:"varint,5,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	User             *User `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginReply) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginReply) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginReply) GetRefreshExpiresIn() int32 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

func (x *LoginReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// RefreshTokenRequest is the input for AuthService.RefreshToken.
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// LogoutRequest is the input for AuthService.Logout.
type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refresh token to revoke. Optional when the caller is authenticated.
	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Revoke every refresh token of the account instead of a single one.
	RevokeAll     bool `protobuf:"varint,2,opt,name=revoke_all,json=revokeAll,proto3" json:"revoke_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LogoutRequest) GetRevokeAll() bool {
	if x != nil {
		return x.RevokeAll
	}
	return false
}

// GetCurrentUserRequest is the input for AuthService.GetCurrentUser.
type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{9}
}

// ChangePasswordRequest is the input for AuthService.ChangePassword.
type ChangePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RSA-OAEP(SHA-256) encrypted, base64 encoded current password.
	CurrentPassword string `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	// RSA-OAEP(SHA-256) encrypted, base64 encoded new password.
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ListSessionsRequest is the input for AuthService.ListSessions.
type ListSessionsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Include sessions that are expired or revoked.
	IncludeInactive bool `protobuf:"varint,3,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSessionsRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

// RevokeSessionRequest is the input for AuthService.RevokeSession.
type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_netdisk_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netdisk_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_netdisk_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_netdisk_v1_auth_proto protoreflect.FileDescriptor

const file_netdisk_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x15netdisk/v1/auth.proto\x12\n" +
	"netdisk.v1\x1a\x15netdisk/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x03\n" +
	"\n" +
	"AuthConfig\x12&\n" +
	"\x0fpassword_key_id\x18\x01 \x01(\tR\rpasswordKeyId\x12+\n" +
	"\x11password_encoding\x18\x02 \x01(\tR\x10passwordEncoding\x12.\n" +
	"\x13password_public_key\x18\x03 \x01(\tR\x11passwordPublicKey\x127\n" +
	"\x18access_token_ttl_seconds\x18\x04 \x01(\x05R\x15accessTokenTtlSeconds\x129\n" +
	"\x19refresh_token_ttl_seconds\x18\x05 \x01(\x05R\x16refreshTokenTtlSeconds\x124\n" +
	"\x16plain_password_allowed\x18\x06 \x01(\bR\x14plainPasswordAllowed\x12;\n" +
	"\vserver_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12.\n" +
	"\x13guest_login_enabled\x18\b \x01(\bR\x11guestLoginEnabled\x12.\n" +
	"\x13min_password_length\x18\t \x01(\x05R\x11minPasswordLength\"\xae\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\x12\x18\n" +
	"\acurrent\x18\b \x01(\bR\acurrent\"e\n" +
	"\n" +
	"SessionSet\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.netdisk.v1.SessionR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x16\n" +
	"\x14GetAuthConfigRequest\"\xa0\x01\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tB\x03\xe0A\x02R\busername\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vremember_me\x18\x05 \x01(\bR\n" +
	"rememberMe\"B\n" +
	"\x11GuestLoginRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"\xe6\x01\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12,\n" +
	"\x12refresh_expires_in\x18\x05 \x01(\x05R\x10refreshExpiresIn\x12$\n" +
	"\x04user\x18\x06 \x01(\v2\x10.netdisk.v1.UserR\x04user\"?\n" +
	"\x13RefreshTokenRequest\x12(\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\x03\xe0A\x02R\frefreshToken\"S\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"revoke_all\x18\x02 \x01(\bR\trevokeAll\"\x17\n" +
	"\x15GetCurrentUserRequest\"o\n" +
	"\x15ChangePasswordRequest\x12.\n" +
	"\x10current_password\x18\x01 \x01(\tB\x03\xe0A\x02R\x0fcurrentPassword\x12&\n" +
	"\fnew_password\x18\x02 \x01(\tB\x03\xe0A\x02R\vnewPassword\"|\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12)\n" +
	"\x10include_inactive\x18\x03 \x01(\bR\x0fincludeInactive\"+\n" +
	"\x14RevokeSessionRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id2\x8d\a\n" +
	"\vAuthService\x12b\n" +
	"\rGetAuthConfig\x12 .netdisk.v1.GetAuthConfigRequest\x1a\x16.netdisk.v1.AuthConfig\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/auth/config\x12T\n" +
	"\x05Login\x12\x18.netdisk.v1.LoginRequest\x1a\x16.netdisk.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12^\n" +
	"\n" +
	"GuestLogin\x12\x1d.netdisk.v1.GuestLoginRequest\x1a\x16.netdisk.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/guest\x12d\n" +
	"\fRefreshToken\x12\x1f.netdisk.v1.RefreshTokenRequest\x1a\x16.netdisk.v1.LoginReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12W\n" +
	"\x06Logout\x12\x19.netdisk.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12Z\n" +
	"\x0eGetCurrentUser\x12!.netdisk.v1.GetCurrentUserRequest\x1a\x10.netdisk.v1.User\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/auth/me\x12p\n" +
	"\x0eChangePassword\x12!.netdisk.v1.ChangePasswordRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/auth/password/change\x12g\n" +
	"\fListSessions\x12\x1f.netdisk.v1.ListSessionsRequest\x1a\x16.netdisk.v1.SessionSet\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/auth/sessions/list\x12n\n" +
	"\rRevokeSession\x12 .netdisk.v1.RevokeSessionRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/auth/sessions/revokeBL\n" +
	"\x14io.nagisa.netdisk.v1B\tAuthProtoP\x01Z\x18nagisa/api/netdisk/v1;v1\xa2\x02\fAPINetdiskV1b\x06proto3"

var (
	file_netdisk_v1_auth_proto_rawDescOnce sync.Once
	file_netdisk_v1_auth_proto_rawDescData []byte
)

func file_netdisk_v1_auth_proto_rawDescGZIP() []byte {
	file_netdisk_v1_auth_proto_rawDescOnce.Do(func() {
		file_netdisk_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_netdisk_v1_auth_proto_rawDesc), len(file_netdisk_v1_auth_proto_rawDesc)))
	})
	return file_netdisk_v1_auth_proto_rawDescData
}

var file_netdisk_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_netdisk_v1_auth_proto_goTypes = []any{
	(*AuthConfig)(nil),            // 0: netdisk.v1.AuthConfig
	(*Session)(nil),               // 1: netdisk.v1.Session
	(*SessionSet)(nil),            // 2: netdisk.v1.SessionSet
	(*GetAuthConfigRequest)(nil),  // 3: netdisk.v1.GetAuthConfigRequest
	(*LoginRequest)(nil),          // 4: netdisk.v1.LoginRequest
	(*GuestLoginRequest)(nil),     // 5: netdisk.v1.GuestLoginRequest
	(*LoginReply)(nil),            // 6: netdisk.v1.LoginReply
	(*RefreshTokenRequest)(nil),   // 7: netdisk.v1.RefreshTokenRequest
	(*LogoutRequest)(nil),         // 8: netdisk.v1.LogoutRequest
	(*GetCurrentUserRequest)(nil), // 9: netdisk.v1.GetCurrentUserRequest
	(*ChangePasswordRequest)(nil), // 10: netdisk.v1.ChangePasswordRequest
	(*ListSessionsRequest)(nil),   // 11: netdisk.v1.ListSessionsRequest
	(*RevokeSessionRequest)(nil),  // 12: netdisk.v1.RevokeSessionRequest
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*User)(nil),                  // 14: netdisk.v1.User
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_netdisk_v1_auth_proto_depIdxs = []int32{
	13, // 0: netdisk.v1.AuthConfig.server_time:type_name -> google.protobuf.Timestamp
	13, // 1: netdisk.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: netdisk.v1.Session.last_used_at:type_name -> google.protobuf.Timestamp
	13, // 3: netdisk.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 4: netdisk.v1.SessionSet.sessions:type_name -> netdisk.v1.Session
	14, // 5: netdisk.v1.LoginReply.user:type_name -> netdisk.v1.User
	3,  // 6: netdisk.v1.AuthService.GetAuthConfig:input_type -> netdisk.v1.GetAuthConfigRequest
	4,  // 7: netdisk.v1.AuthService.Login:input_type -> netdisk.v1.LoginRequest
	5,  // 8: netdisk.v1.AuthService.GuestLogin:input_type -> netdisk.v1.GuestLoginRequest
	7,  // 9: netdisk.v1.AuthService.RefreshToken:input_type -> netdisk.v1.RefreshTokenRequest
	8,  // 10: netdisk.v1.AuthService.Logout:input_type -> netdisk.v1.LogoutRequest
	9,  // 11: netdisk.v1.AuthService.GetCurrentUser:input_type -> netdisk.v1.GetCurrentUserRequest
	10, // 12: netdisk.v1.AuthService.ChangePassword:input_type -> netdisk.v1.ChangePasswordRequest
	11, // 13: netdisk.v1.AuthService.ListSessions:input_type -> netdisk.v1.ListSessionsRequest
	12, // 14: netdisk.v1.AuthService.RevokeSession:input_type -> netdisk.v1.RevokeSessionRequest
	0,  // 15: netdisk.v1.AuthService.GetAuthConfig:output_type -> netdisk.v1.AuthConfig
	6,  // 16: netdisk.v1.AuthService.Login:output_type -> netdisk.v1.LoginReply
	6,  // 17: netdisk.v1.AuthService.GuestLogin:output_type -> netdisk.v1.LoginReply
	6,  // 18: netdisk.v1.AuthService.RefreshToken:output_type -> netdisk.v1.LoginReply
	15, // 19: netdisk.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	14, // 20: netdisk.v1.AuthService.GetCurrentUser:output_type -> netdisk.v1.User
	15, // 21: netdisk.v1.AuthService.ChangePassword:output_type -> google.protobuf.Empty
	2,  // 22: netdisk.v1.AuthService.ListSessions:output_type -> netdisk.v1.SessionSet
	15, // 23: netdisk.v1.AuthService.RevokeSession:output_type -> google.protobuf.Empty
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_netdisk_v1_auth_proto_init() }
func file_netdisk_v1_auth_proto_init() {
	if File_netdisk_v1_auth_proto != nil {
		return
	}
	file_netdisk_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_netdisk_v1_auth_proto_rawDesc), len(file_netdisk_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_netdisk_v1_auth_proto_goTypes,
		DependencyIndexes: file_netdisk_v1_auth_proto_depIdxs,
		MessageInfos:      file_netdisk_v1_auth_proto_msgTypes,
	}.Build()
	File_netdisk_v1_auth_proto = out.File
	file_netdisk_v1_auth_proto_goTypes = nil
	file_netdisk_v1_auth_proto_depIdxs = nil
}
