// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: netdisk/v1/file.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_InitiateUpload_FullMethodName    = "/netdisk.v1.FileService/InitiateUpload"
	FileService_ListUploads_FullMethodName       = "/netdisk.v1.FileService/ListUploads"
	FileService_CompleteUpload_FullMethodName    = "/netdisk.v1.FileService/CompleteUpload"
	FileService_AbortUpload_FullMethodName       = "/netdisk.v1.FileService/AbortUpload"
	FileService_ConfirmUploadPart_FullMethodName = "/netdisk.v1.FileService/ConfirmUploadPart"
	FileService_UploadSmallFile_FullMethodName   = "/netdisk.v1.FileService/UploadSmallFile"
	FileService_GetUpload_FullMethodName         = "/netdisk.v1.FileService/GetUpload"
	FileService_ListUploadParts_FullMethodName   = "/netdisk.v1.FileService/ListUploadParts"
	FileService_UploadChunk_FullMethodName       = "/netdisk.v1.FileService/UploadChunk"
	FileService_GetDownloadUrl_FullMethodName    = "/netdisk.v1.FileService/GetDownloadUrl"
	FileService_GetArchiveUrl_FullMethodName     = "/netdisk.v1.FileService/GetArchiveUrl"
	FileService_GetPreviewUrl_FullMethodName     = "/netdisk.v1.FileService/GetPreviewUrl"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FileService covers content transfer: resumable multipart upload, signed
// download URLs and previews.
//
// Uploads are staged in object storage and only become visible as a node when
// CompleteUpload succeeds. The commit runs in a single database transaction
// that re-checks the destination name, the quota and the declared checksum, so
// a failed or abandoned upload never leaves a half-created node behind.
//
// Two transports are available for part payloads:
//   - UPLOAD_MODE_PRESIGNED PUTs each part straight to object storage with a
//     presigned URL, which never routes bytes through this server;
//   - UPLOAD_MODE_PROXY streams each part through UploadPart, for deployments
//     where object storage is not reachable by clients.
//
// A raw streaming binding exists for browser clients that cannot speak proto
// JSON: PUT /v1/files/uploads/{upload_id}/parts/{part_number}/raw accepts an
// application/octet-stream body, and GET /v1/files/{node_id}/content streams
// the original bytes with byte-range support.
type FileServiceClient interface {
	// InitiateUpload opens a multipart upload session. When a session with the
	// same parent, name and owner is still pending it is returned instead of a
	// new one, which makes retries and resumes idempotent.
	InitiateUpload(ctx context.Context, in *InitiateUploadRequest, opts ...grpc.CallOption) (*UploadSession, error)
	// ListUploads returns the caller's upload sessions.
	ListUploads(ctx context.Context, in *ListUploadsRequest, opts ...grpc.CallOption) (*UploadSessionSet, error)
	// CompleteUpload verifies every declared part, assembles the object and
	// commits the node in one transaction.
	// Returns UPLOAD_INCOMPLETE when parts are missing or their sizes do not add
	// up, PRECONDITION_FAILED when the checksum does not match, and
	// NAME_CONFLICT when the destination name was taken meanwhile.
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*Node, error)
	// AbortUpload cancels a session and reclaims every staged part.
	AbortUpload(ctx context.Context, in *AbortUploadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ConfirmUploadPart records the etag produced by a direct-to-storage part
	// upload. Only meaningful in UPLOAD_MODE_PRESIGNED.
	ConfirmUploadPart(ctx context.Context, in *ConfirmUploadPartRequest, opts ...grpc.CallOption) (*UploadPart, error)
	// UploadSmallFile stores a payload carried inside the request. Intended for
	// files at or below the max_inline_size advertised by SystemService, which
	// defaults to 4 MiB.
	UploadSmallFile(ctx context.Context, in *UploadSmallFileRequest, opts ...grpc.CallOption) (*Node, error)
	// GetUpload returns one upload session, including the parts already stored.
	GetUpload(ctx context.Context, in *GetUploadRequest, opts ...grpc.CallOption) (*UploadSession, error)
	// ListUploadParts returns the parts of a session, which lets a client resume
	// without re-sending completed parts.
	ListUploadParts(ctx context.Context, in *ListUploadPartsRequest, opts ...grpc.CallOption) (*UploadPartSet, error)
	// UploadChunk streams one part through the server. part_number is one-based
	// and must not exceed UploadSession.total_parts. Content type is inferred
	// from the parent session.
	UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadPart, error)
	// GetDownloadUrl returns a signed URL for the original bytes of a file
	// node. In a presigned deployment the URL points at object storage, so the
	// download never traverses this server. The URL encodes the node id, the
	// caller, the expiry and the disposition, and is validated again when it is
	// redeemed.
	GetDownloadUrl(ctx context.Context, in *GetDownloadUrlRequest, opts ...grpc.CallOption) (*SignedUrl, error)
	// GetArchiveUrl returns a signed URL that streams a folder, or a file, as a
	// zip archive. Large folders are streamed on the fly rather than materialised.
	GetArchiveUrl(ctx context.Context, in *GetArchiveUrlRequest, opts ...grpc.CallOption) (*SignedUrl, error)
	// GetPreviewUrl returns a signed URL for an inline preview or a thumbnail.
	// Returns UNSUPPORTED when no preview can be produced for the mime type.
	GetPreviewUrl(ctx context.Context, in *GetPreviewUrlRequest, opts ...grpc.CallOption) (*SignedUrl, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) InitiateUpload(ctx context.Context, in *InitiateUploadRequest, opts ...grpc.CallOption) (*UploadSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSession)
	err := c.cc.Invoke(ctx, FileService_InitiateUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListUploads(ctx context.Context, in *ListUploadsRequest, opts ...grpc.CallOption) (*UploadSessionSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSessionSet)
	err := c.cc.Invoke(ctx, FileService_ListUploads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, FileService_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) AbortUpload(ctx context.Context, in *AbortUploadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FileService_AbortUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ConfirmUploadPart(ctx context.Context, in *ConfirmUploadPartRequest, opts ...grpc.CallOption) (*UploadPart, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPart)
	err := c.cc.Invoke(ctx, FileService_ConfirmUploadPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UploadSmallFile(ctx context.Context, in *UploadSmallFileRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, FileService_UploadSmallFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetUpload(ctx context.Context, in *GetUploadRequest, opts ...grpc.CallOption) (*UploadSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSession)
	err := c.cc.Invoke(ctx, FileService_GetUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListUploadParts(ctx context.Context, in *ListUploadPartsRequest, opts ...grpc.CallOption) (*UploadPartSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPartSet)
	err := c.cc.Invoke(ctx, FileService_ListUploadParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadPart, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPart)
	err := c.cc.Invoke(ctx, FileService_UploadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetDownloadUrl(ctx context.Context, in *GetDownloadUrlRequest, opts ...grpc.CallOption) (*SignedUrl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedUrl)
	err := c.cc.Invoke(ctx, FileService_GetDownloadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetArchiveUrl(ctx context.Context, in *GetArchiveUrlRequest, opts ...grpc.CallOption) (*SignedUrl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedUrl)
	err := c.cc.Invoke(ctx, FileService_GetArchiveUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetPreviewUrl(ctx context.Context, in *GetPreviewUrlRequest, opts ...grpc.CallOption) (*SignedUrl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedUrl)
	err := c.cc.Invoke(ctx, FileService_GetPreviewUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
//
// FileService covers content transfer: resumable multipart upload, signed
// download URLs and previews.
//
// Uploads are staged in object storage and only become visible as a node when
// CompleteUpload succeeds. The commit runs in a single database transaction
// that re-checks the destination name, the quota and the declared checksum, so
// a failed or abandoned upload never leaves a half-created node behind.
//
// Two transports are available for part payloads:
//   - UPLOAD_MODE_PRESIGNED PUTs each part straight to object storage with a
//     presigned URL, which never routes bytes through this server;
//   - UPLOAD_MODE_PROXY streams each part through UploadPart, for deployments
//     where object storage is not reachable by clients.
//
// A raw streaming binding exists for browser clients that cannot speak proto
// JSON: PUT /v1/files/uploads/{upload_id}/parts/{part_number}/raw accepts an
// application/octet-stream body, and GET /v1/files/{node_id}/content streams
// the original bytes with byte-range support.
type FileServiceServer interface {
	// InitiateUpload opens a multipart upload session. When a session with the
	// same parent, name and owner is still pending it is returned instead of a
	// new one, which makes retries and resumes idempotent.
	InitiateUpload(context.Context, *InitiateUploadRequest) (*UploadSession, error)
	// ListUploads returns the caller's upload sessions.
	ListUploads(context.Context, *ListUploadsRequest) (*UploadSessionSet, error)
	// CompleteUpload verifies every declared part, assembles the object and
	// commits the node in one transaction.
	// Returns UPLOAD_INCOMPLETE when parts are missing or their sizes do not add
	// up, PRECONDITION_FAILED when the checksum does not match, and
	// NAME_CONFLICT when the destination name was taken meanwhile.
	CompleteUpload(context.Context, *CompleteUploadRequest) (*Node, error)
	// AbortUpload cancels a session and reclaims every staged part.
	AbortUpload(context.Context, *AbortUploadRequest) (*emptypb.Empty, error)
	// ConfirmUploadPart records the etag produced by a direct-to-storage part
	// upload. Only meaningful in UPLOAD_MODE_PRESIGNED.
	ConfirmUploadPart(context.Context, *ConfirmUploadPartRequest) (*UploadPart, error)
	// UploadSmallFile stores a payload carried inside the request. Intended for
	// files at or below the max_inline_size advertised by SystemService, which
	// defaults to 4 MiB.
	UploadSmallFile(context.Context, *UploadSmallFileRequest) (*Node, error)
	// GetUpload returns one upload session, including the parts already stored.
	GetUpload(context.Context, *GetUploadRequest) (*UploadSession, error)
	// ListUploadParts returns the parts of a session, which lets a client resume
	// without re-sending completed parts.
	ListUploadParts(context.Context, *ListUploadPartsRequest) (*UploadPartSet, error)
	// UploadChunk streams one part through the server. part_number is one-based
	// and must not exceed UploadSession.total_parts. Content type is inferred
	// from the parent session.
	UploadChunk(context.Context, *UploadChunkRequest) (*UploadPart, error)
	// GetDownloadUrl returns a signed URL for the original bytes of a file
	// node. In a presigned deployment the URL points at object storage, so the
	// download never traverses this server. The URL encodes the node id, the
	// caller, the expiry and the disposition, and is validated again when it is
	// redeemed.
	GetDownloadUrl(context.Context, *GetDownloadUrlRequest) (*SignedUrl, error)
	// GetArchiveUrl returns a signed URL that streams a folder, or a file, as a
	// zip archive. Large folders are streamed on the fly rather than materialised.
	GetArchiveUrl(context.Context, *GetArchiveUrlRequest) (*SignedUrl, error)
	// GetPreviewUrl returns a signed URL for an inline preview or a thumbnail.
	// Returns UNSUPPORTED when no preview can be produced for the mime type.
	GetPreviewUrl(context.Context, *GetPreviewUrlRequest) (*SignedUrl, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) InitiateUpload(context.Context, *InitiateUploadRequest) (*UploadSession, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateUpload not implemented")
}
func (UnimplementedFileServiceServer) ListUploads(context.Context, *ListUploadsRequest) (*UploadSessionSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUploads not implemented")
}
func (UnimplementedFileServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedFileServiceServer) AbortUpload(context.Context, *AbortUploadRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortUpload not implemented")
}
func (UnimplementedFileServiceServer) ConfirmUploadPart(context.Context, *ConfirmUploadPartRequest) (*UploadPart, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmUploadPart not implemented")
}
func (UnimplementedFileServiceServer) UploadSmallFile(context.Context, *UploadSmallFileRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSmallFile not implemented")
}
func (UnimplementedFileServiceServer) GetUpload(context.Context, *GetUploadRequest) (*UploadSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpload not implemented")
}
func (UnimplementedFileServiceServer) ListUploadParts(context.Context, *ListUploadPartsRequest) (*UploadPartSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUploadParts not implemented")
}
func (UnimplementedFileServiceServer) UploadChunk(context.Context, *UploadChunkRequest) (*UploadPart, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadChunk not implemented")
}
func (UnimplementedFileServiceServer) GetDownloadUrl(context.Context, *GetDownloadUrlRequest) (*SignedUrl, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDownloadUrl not implemented")
}
func (UnimplementedFileServiceServer) GetArchiveUrl(context.Context, *GetArchiveUrlRequest) (*SignedUrl, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArchiveUrl not implemented")
}
func (UnimplementedFileServiceServer) GetPreviewUrl(context.Context, *GetPreviewUrlRequest) (*SignedUrl, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreviewUrl not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_InitiateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).InitiateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_InitiateUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).InitiateUpload(ctx, req.(*InitiateUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListUploads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUploadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListUploads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListUploads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListUploads(ctx, req.(*ListUploadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_AbortUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).AbortUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_AbortUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).AbortUpload(ctx, req.(*AbortUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ConfirmUploadPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUploadPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ConfirmUploadPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ConfirmUploadPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ConfirmUploadPart(ctx, req.(*ConfirmUploadPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UploadSmallFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSmallFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadSmallFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadSmallFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadSmallFile(ctx, req.(*UploadSmallFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetUpload(ctx, req.(*GetUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListUploadParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUploadPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListUploadParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListUploadParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListUploadParts(ctx, req.(*ListUploadPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UploadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadChunk(ctx, req.(*UploadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetDownloadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetDownloadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetDownloadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetDownloadUrl(ctx, req.(*GetDownloadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetArchiveUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArchiveUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetArchiveUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetArchiveUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetArchiveUrl(ctx, req.(*GetArchiveUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetPreviewUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreviewUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetPreviewUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetPreviewUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetPreviewUrl(ctx, req.(*GetPreviewUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netdisk.v1.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateUpload",
			Handler:    _FileService_InitiateUpload_Handler,
		},
		{
			MethodName: "ListUploads",
			Handler:    _FileService_ListUploads_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _FileService_CompleteUpload_Handler,
		},
		{
			MethodName: "AbortUpload",
			Handler:    _FileService_AbortUpload_Handler,
		},
		{
			MethodName: "ConfirmUploadPart",
			Handler:    _FileService_ConfirmUploadPart_Handler,
		},
		{
			MethodName: "UploadSmallFile",
			Handler:    _FileService_UploadSmallFile_Handler,
		},
		{
			MethodName: "GetUpload",
			Handler:    _FileService_GetUpload_Handler,
		},
		{
			MethodName: "ListUploadParts",
			Handler:    _FileService_ListUploadParts_Handler,
		},
		{
			MethodName: "UploadChunk",
			Handler:    _FileService_UploadChunk_Handler,
		},
		{
			MethodName: "GetDownloadUrl",
			Handler:    _FileService_GetDownloadUrl_Handler,
		},
		{
			MethodName: "GetArchiveUrl",
			Handler:    _FileService_GetArchiveUrl_Handler,
		},
		{
			MethodName: "GetPreviewUrl",
			Handler:    _FileService_GetPreviewUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netdisk/v1/file.proto",
}
