// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: netdisk/v1/file.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationFileServiceAbortUpload = "/netdisk.v1.FileService/AbortUpload"
const OperationFileServiceCompleteUpload = "/netdisk.v1.FileService/CompleteUpload"
const OperationFileServiceConfirmUploadPart = "/netdisk.v1.FileService/ConfirmUploadPart"
const OperationFileServiceGetArchiveUrl = "/netdisk.v1.FileService/GetArchiveUrl"
const OperationFileServiceGetDownloadUrl = "/netdisk.v1.FileService/GetDownloadUrl"
const OperationFileServiceGetPreviewUrl = "/netdisk.v1.FileService/GetPreviewUrl"
const OperationFileServiceGetUpload = "/netdisk.v1.FileService/GetUpload"
const OperationFileServiceInitiateUpload = "/netdisk.v1.FileService/InitiateUpload"
const OperationFileServiceListUploadParts = "/netdisk.v1.FileService/ListUploadParts"
const OperationFileServiceListUploads = "/netdisk.v1.FileService/ListUploads"
const OperationFileServiceUploadChunk = "/netdisk.v1.FileService/UploadChunk"
const OperationFileServiceUploadSmallFile = "/netdisk.v1.FileService/UploadSmallFile"

type FileServiceHTTPServer interface {
	// AbortUpload AbortUpload cancels a session and reclaims every staged part.
	AbortUpload(context.Context, *AbortUploadRequest) (*emptypb.Empty, error)
	// CompleteUpload CompleteUpload verifies every declared part, assembles the object and
	// commits the node in one transaction.
	// Returns UPLOAD_INCOMPLETE when parts are missing or their sizes do not add
	// up, PRECONDITION_FAILED when the checksum does not match, and
	// NAME_CONFLICT when the destination name was taken meanwhile.
	CompleteUpload(context.Context, *CompleteUploadRequest) (*Node, error)
	// ConfirmUploadPart ConfirmUploadPart records the etag produced by a direct-to-storage part
	// upload. Only meaningful in UPLOAD_MODE_PRESIGNED.
	ConfirmUploadPart(context.Context, *ConfirmUploadPartRequest) (*UploadPart, error)
	// GetArchiveUrl GetArchiveUrl returns a signed URL that streams a folder, or a file, as a
	// zip archive. Large folders are streamed on the fly rather than materialised.
	GetArchiveUrl(context.Context, *GetArchiveUrlRequest) (*SignedUrl, error)
	// GetDownloadUrl GetDownloadUrl returns a signed URL for the original bytes of a file
	// node. In a presigned deployment the URL points at object storage, so the
	// download never traverses this server. The URL encodes the node id, the
	// caller, the expiry and the disposition, and is validated again when it is
	// redeemed.
	GetDownloadUrl(context.Context, *GetDownloadUrlRequest) (*SignedUrl, error)
	// GetPreviewUrl GetPreviewUrl returns a signed URL for an inline preview or a thumbnail.
	// Returns UNSUPPORTED when no preview can be produced for the mime type.
	GetPreviewUrl(context.Context, *GetPreviewUrlRequest) (*SignedUrl, error)
	// GetUpload GetUpload returns one upload session, including the parts already stored.
	GetUpload(context.Context, *GetUploadRequest) (*UploadSession, error)
	// InitiateUpload InitiateUpload opens a multipart upload session. When a session with the
	// same parent, name and owner is still pending it is returned instead of a
	// new one, which makes retries and resumes idempotent.
	InitiateUpload(context.Context, *InitiateUploadRequest) (*UploadSession, error)
	// ListUploadParts ListUploadParts returns the parts of a session, which lets a client resume
	// without re-sending completed parts.
	ListUploadParts(context.Context, *ListUploadPartsRequest) (*UploadPartSet, error)
	// ListUploads ListUploads returns the caller's upload sessions.
	ListUploads(context.Context, *ListUploadsRequest) (*UploadSessionSet, error)
	// UploadChunk UploadChunk streams one part through the server. part_number is one-based
	// and must not exceed UploadSession.total_parts. Content type is inferred
	// from the parent session.
	UploadChunk(context.Context, *UploadChunkRequest) (*UploadPart, error)
	// UploadSmallFile UploadSmallFile stores a payload carried inside the request. Intended for
	// files at or below the max_inline_size advertised by SystemService, which
	// defaults to 4 MiB.
	UploadSmallFile(context.Context, *UploadSmallFileRequest) (*Node, error)
}

func RegisterFileServiceHTTPServer(s *http.Server, srv FileServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/files/uploads/create", _FileService_InitiateUpload0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/files/uploads/list", _FileService_ListUploads0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/files/uploads/complete", _FileService_CompleteUpload0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/files/uploads/abort", _FileService_AbortUpload0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/files/uploads/parts/confirm", _FileService_ConfirmUploadPart0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/files/upload", _FileService_UploadSmallFile0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/files/uploads/{id}", _FileService_GetUpload0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/files/uploads/{upload_id}/parts", _FileService_ListUploadParts0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/files/uploads/{upload_id}/parts/{part_number}", _FileService_UploadChunk0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/files/{node_id}/download-url", _FileService_GetDownloadUrl0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/files/{node_id}/archive-url", _FileService_GetArchiveUrl0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/files/{node_id}/preview-url", _FileService_GetPreviewUrl0_HTTP_Handler(srv))
}

func _FileService_InitiateUpload0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InitiateUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceInitiateUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InitiateUpload(ctx, req.(*InitiateUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadSession)
		return ctx.Result(200, reply)
	}
}

func _FileService_ListUploads0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUploadsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceListUploads)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUploads(ctx, req.(*ListUploadsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadSessionSet)
		return ctx.Result(200, reply)
	}
}

func _FileService_CompleteUpload0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceCompleteUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteUpload(ctx, req.(*CompleteUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Node)
		return ctx.Result(200, reply)
	}
}

func _FileService_AbortUpload0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AbortUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceAbortUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AbortUpload(ctx, req.(*AbortUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _FileService_ConfirmUploadPart0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmUploadPartRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceConfirmUploadPart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmUploadPart(ctx, req.(*ConfirmUploadPartRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadPart)
		return ctx.Result(200, reply)
	}
}

func _FileService_UploadSmallFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadSmallFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceUploadSmallFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadSmallFile(ctx, req.(*UploadSmallFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Node)
		return ctx.Result(200, reply)
	}
}

func _FileService_GetUpload0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUploadRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceGetUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUpload(ctx, req.(*GetUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadSession)
		return ctx.Result(200, reply)
	}
}

func _FileService_ListUploadParts0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUploadPartsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceListUploadParts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUploadParts(ctx, req.(*ListUploadPartsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadPartSet)
		return ctx.Result(200, reply)
	}
}

func _FileService_UploadChunk0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadChunkRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceUploadChunk)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadChunk(ctx, req.(*UploadChunkRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadPart)
		return ctx.Result(200, reply)
	}
}

func _FileService_GetDownloadUrl0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDownloadUrlRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceGetDownloadUrl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDownloadUrl(ctx, req.(*GetDownloadUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SignedUrl)
		return ctx.Result(200, reply)
	}
}

func _FileService_GetArchiveUrl0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArchiveUrlRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceGetArchiveUrl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArchiveUrl(ctx, req.(*GetArchiveUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SignedUrl)
		return ctx.Result(200, reply)
	}
}

func _FileService_GetPreviewUrl0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPreviewUrlRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceGetPreviewUrl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPreviewUrl(ctx, req.(*GetPreviewUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SignedUrl)
		return ctx.Result(200, reply)
	}
}

type FileServiceHTTPClient interface {
	// AbortUpload AbortUpload cancels a session and reclaims every staged part.
	AbortUpload(ctx context.Context, req *AbortUploadRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// CompleteUpload CompleteUpload verifies every declared part, assembles the object and
	// commits the node in one transaction.
	// Returns UPLOAD_INCOMPLETE when parts are missing or their sizes do not add
	// up, PRECONDITION_FAILED when the checksum does not match, and
	// NAME_CONFLICT when the destination name was taken meanwhile.
	CompleteUpload(ctx context.Context, req *CompleteUploadRequest, opts ...http.CallOption) (rsp *Node, err error)
	// ConfirmUploadPart ConfirmUploadPart records the etag produced by a direct-to-storage part
	// upload. Only meaningful in UPLOAD_MODE_PRESIGNED.
	ConfirmUploadPart(ctx context.Context, req *ConfirmUploadPartRequest, opts ...http.CallOption) (rsp *UploadPart, err error)
	// GetArchiveUrl GetArchiveUrl returns a signed URL that streams a folder, or a file, as a
	// zip archive. Large folders are streamed on the fly rather than materialised.
	GetArchiveUrl(ctx context.Context, req *GetArchiveUrlRequest, opts ...http.CallOption) (rsp *SignedUrl, err error)
	// GetDownloadUrl GetDownloadUrl returns a signed URL for the original bytes of a file
	// node. In a presigned deployment the URL points at object storage, so the
	// download never traverses this server. The URL encodes the node id, the
	// caller, the expiry and the disposition, and is validated again when it is
	// redeemed.
	GetDownloadUrl(ctx context.Context, req *GetDownloadUrlRequest, opts ...http.CallOption) (rsp *SignedUrl, err error)
	// GetPreviewUrl GetPreviewUrl returns a signed URL for an inline preview or a thumbnail.
	// Returns UNSUPPORTED when no preview can be produced for the mime type.
	GetPreviewUrl(ctx context.Context, req *GetPreviewUrlRequest, opts ...http.CallOption) (rsp *SignedUrl, err error)
	// GetUpload GetUpload returns one upload session, including the parts already stored.
	GetUpload(ctx context.Context, req *GetUploadRequest, opts ...http.CallOption) (rsp *UploadSession, err error)
	// InitiateUpload InitiateUpload opens a multipart upload session. When a session with the
	// same parent, name and owner is still pending it is returned instead of a
	// new one, which makes retries and resumes idempotent.
	InitiateUpload(ctx context.Context, req *InitiateUploadRequest, opts ...http.CallOption) (rsp *UploadSession, err error)
	// ListUploadParts ListUploadParts returns the parts of a session, which lets a client resume
	// without re-sending completed parts.
	ListUploadParts(ctx context.Context, req *ListUploadPartsRequest, opts ...http.CallOption) (rsp *UploadPartSet, err error)
	// ListUploads ListUploads returns the caller's upload sessions.
	ListUploads(ctx context.Context, req *ListUploadsRequest, opts ...http.CallOption) (rsp *UploadSessionSet, err error)
	// UploadChunk UploadChunk streams one part through the server. part_number is one-based
	// and must not exceed UploadSession.total_parts. Content type is inferred
	// from the parent session.
	UploadChunk(ctx context.Context, req *UploadChunkRequest, opts ...http.CallOption) (rsp *UploadPart, err error)
	// UploadSmallFile UploadSmallFile stores a payload carried inside the request. Intended for
	// files at or below the max_inline_size advertised by SystemService, which
	// defaults to 4 MiB.
	UploadSmallFile(ctx context.Context, req *UploadSmallFileRequest, opts ...http.CallOption) (rsp *Node, err error)
}

type FileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewFileServiceHTTPClient(client *http.Client) FileServiceHTTPClient {
	return &FileServiceHTTPClientImpl{client}
}

// AbortUpload AbortUpload cancels a session and reclaims every staged part.
func (c *FileServiceHTTPClientImpl) AbortUpload(ctx context.Context, in *AbortUploadRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/files/uploads/abort"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceAbortUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CompleteUpload CompleteUpload verifies every declared part, assembles the object and
// commits the node in one transaction.
// Returns UPLOAD_INCOMPLETE when parts are missing or their sizes do not add
// up, PRECONDITION_FAILED when the checksum does not match, and
// NAME_CONFLICT when the destination name was taken meanwhile.
func (c *FileServiceHTTPClientImpl) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...http.CallOption) (*Node, error) {
	var out Node
	pattern := "/v1/files/uploads/complete"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceCompleteUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ConfirmUploadPart ConfirmUploadPart records the etag produced by a direct-to-storage part
// upload. Only meaningful in UPLOAD_MODE_PRESIGNED.
func (c *FileServiceHTTPClientImpl) ConfirmUploadPart(ctx context.Context, in *ConfirmUploadPartRequest, opts ...http.CallOption) (*UploadPart, error) {
	var out UploadPart
	pattern := "/v1/files/uploads/parts/confirm"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceConfirmUploadPart),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetArchiveUrl GetArchiveUrl returns a signed URL that streams a folder, or a file, as a
// zip archive. Large folders are streamed on the fly rather than materialised.
func (c *FileServiceHTTPClientImpl) GetArchiveUrl(ctx context.Context, in *GetArchiveUrlRequest, opts ...http.CallOption) (*SignedUrl, error) {
	var out SignedUrl
	pattern := "/v1/files/{node_id}/archive-url"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceGetArchiveUrl),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDownloadUrl GetDownloadUrl returns a signed URL for the original bytes of a file
// node. In a presigned deployment the URL points at object storage, so the
// download never traverses this server. The URL encodes the node id, the
// caller, the expiry and the disposition, and is validated again when it is
// redeemed.
func (c *FileServiceHTTPClientImpl) GetDownloadUrl(ctx context.Context, in *GetDownloadUrlRequest, opts ...http.CallOption) (*SignedUrl, error) {
	var out SignedUrl
	pattern := "/v1/files/{node_id}/download-url"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceGetDownloadUrl),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPreviewUrl GetPreviewUrl returns a signed URL for an inline preview or a thumbnail.
// Returns UNSUPPORTED when no preview can be produced for the mime type.
func (c *FileServiceHTTPClientImpl) GetPreviewUrl(ctx context.Context, in *GetPreviewUrlRequest, opts ...http.CallOption) (*SignedUrl, error) {
	var out SignedUrl
	pattern := "/v1/files/{node_id}/preview-url"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceGetPreviewUrl),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUpload GetUpload returns one upload session, including the parts already stored.
func (c *FileServiceHTTPClientImpl) GetUpload(ctx context.Context, in *GetUploadRequest, opts ...http.CallOption) (*UploadSession, error) {
	var out UploadSession
	pattern := "/v1/files/uploads/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceGetUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InitiateUpload InitiateUpload opens a multipart upload session. When a session with the
// same parent, name and owner is still pending it is returned instead of a
// new one, which makes retries and resumes idempotent.
func (c *FileServiceHTTPClientImpl) InitiateUpload(ctx context.Context, in *InitiateUploadRequest, opts ...http.CallOption) (*UploadSession, error) {
	var out UploadSession
	pattern := "/v1/files/uploads/create"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceInitiateUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUploadParts ListUploadParts returns the parts of a session, which lets a client resume
// without re-sending completed parts.
func (c *FileServiceHTTPClientImpl) ListUploadParts(ctx context.Context, in *ListUploadPartsRequest, opts ...http.CallOption) (*UploadPartSet, error) {
	var out UploadPartSet
	pattern := "/v1/files/uploads/{upload_id}/parts"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceListUploadParts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUploads ListUploads returns the caller's upload sessions.
func (c *FileServiceHTTPClientImpl) ListUploads(ctx context.Context, in *ListUploadsRequest, opts ...http.CallOption) (*UploadSessionSet, error) {
	var out UploadSessionSet
	pattern := "/v1/files/uploads/list"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceListUploads),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadChunk UploadChunk streams one part through the server. part_number is one-based
// and must not exceed UploadSession.total_parts. Content type is inferred
// from the parent session.
func (c *FileServiceHTTPClientImpl) UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...http.CallOption) (*UploadPart, error) {
	var out UploadPart
	pattern := "/v1/files/uploads/{upload_id}/parts/{part_number}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceUploadChunk),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadSmallFile UploadSmallFile stores a payload carried inside the request. Intended for
// files at or below the max_inline_size advertised by SystemService, which
// defaults to 4 MiB.
func (c *FileServiceHTTPClientImpl) UploadSmallFile(ctx context.Context, in *UploadSmallFileRequest, opts ...http.CallOption) (*Node, error) {
	var out Node
	pattern := "/v1/files/upload"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceUploadSmallFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
