// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: netdisk/v1/node.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_ListNodes_FullMethodName          = "/netdisk.v1.NodeService/ListNodes"
	NodeService_SearchNodes_FullMethodName        = "/netdisk.v1.NodeService/SearchNodes"
	NodeService_GetNodeTree_FullMethodName        = "/netdisk.v1.NodeService/GetNodeTree"
	NodeService_ListTrash_FullMethodName          = "/netdisk.v1.NodeService/ListTrash"
	NodeService_GetNode_FullMethodName            = "/netdisk.v1.NodeService/GetNode"
	NodeService_GetNodePath_FullMethodName        = "/netdisk.v1.NodeService/GetNodePath"
	NodeService_GetNodeStats_FullMethodName       = "/netdisk.v1.NodeService/GetNodeStats"
	NodeService_GetNodeAcl_FullMethodName         = "/netdisk.v1.NodeService/GetNodeAcl"
	NodeService_CreateFolder_FullMethodName       = "/netdisk.v1.NodeService/CreateFolder"
	NodeService_UpdateNode_FullMethodName         = "/netdisk.v1.NodeService/UpdateNode"
	NodeService_SetNodeAcl_FullMethodName         = "/netdisk.v1.NodeService/SetNodeAcl"
	NodeService_UnlockNode_FullMethodName         = "/netdisk.v1.NodeService/UnlockNode"
	NodeService_MoveNodes_FullMethodName          = "/netdisk.v1.NodeService/MoveNodes"
	NodeService_CopyNodes_FullMethodName          = "/netdisk.v1.NodeService/CopyNodes"
	NodeService_DeleteNodes_FullMethodName        = "/netdisk.v1.NodeService/DeleteNodes"
	NodeService_RestoreNodes_FullMethodName       = "/netdisk.v1.NodeService/RestoreNodes"
	NodeService_PurgeNodes_FullMethodName         = "/netdisk.v1.NodeService/PurgeNodes"
	NodeService_EmptyTrash_FullMethodName         = "/netdisk.v1.NodeService/EmptyTrash"
	NodeService_ListNodeVersions_FullMethodName   = "/netdisk.v1.NodeService/ListNodeVersions"
	NodeService_RestoreNodeVersion_FullMethodName = "/netdisk.v1.NodeService/RestoreNodeVersion"
	NodeService_DeleteNodeVersion_FullMethodName  = "/netdisk.v1.NodeService/DeleteNodeVersion"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService manages the file tree. Folders are modelled as nodes of kind
// NODE_KIND_FOLDER, so description, ACL, visibility and password protection
// apply to files and folders alike.
//
// Access to a node is decided in this order:
//  1. the caller must hold PERMISSION_VIEW (or the permission matching the
//     operation) in its account permission set;
//  2. the owner of a node always holds every permission on it;
//  3. an explicit DENY entry on the node or any ancestor wins immediately;
//  4. an explicit ALLOW entry on the node or an inheriting ancestor grants
//     the permission;
//  5. VISIBILITY_PUBLIC grants read access to anybody, VISIBILITY_INTERNAL
//     grants read access to any authenticated caller, VISIBILITY_PRIVATE
//     grants nothing beyond the rules above.
//  6. a password protected folder additionally requires a node unlock token
//     obtained from UnlockNode, sent in the X-Node-Token header.
type NodeServiceClient interface {
	// ListNodes returns the children of a folder, or the root listing when
	// parent_id is empty. Set recursive to walk the whole subtree.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*NodeSet, error)
	// SearchNodes performs a tree-wide search over names and descriptions.
	SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*NodeSet, error)
	// GetNodeTree returns a folder subtree expanded to the requested depth in a
	// single round trip.
	GetNodeTree(ctx context.Context, in *GetNodeTreeRequest, opts ...grpc.CallOption) (*NodeTree, error)
	// ListTrash returns the trashed nodes visible to the caller. Entries are
	// listed one level at a time, so a deleted folder shows up without its
	// contents: the top entry of every trashed subtree comes first, and
	// original_parent_id walks into one of those folders.
	ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*NodeSet, error)
	// GetNode returns a single node by id.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error)
	// GetNodePath returns the breadcrumb from the root to the node.
	GetNodePath(ctx context.Context, in *GetNodePathRequest, opts ...grpc.CallOption) (*NodePath, error)
	// GetNodeStats returns aggregate counters for the node subtree.
	GetNodeStats(ctx context.Context, in *GetNodeStatsRequest, opts ...grpc.CallOption) (*NodeStats, error)
	// GetNodeAcl returns the ACL entries attached to a node together with the
	// entries inherited from ancestors and the caller's effective permissions.
	GetNodeAcl(ctx context.Context, in *GetNodeAclRequest, opts ...grpc.CallOption) (*NodeAcl, error)
	// CreateFolder creates a folder. The folder may carry a description, a
	// visibility, a password and, through SetNodeAcl, an allow/deny list.
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*Node, error)
	// UpdateNode applies a partial update to a node. Supported paths: `name`,
	// `description`, `visibility`, `metadata`, `password`, `remove_password`,
	// `parent_id`. Renaming or moving requires PERMISSION_EDIT on the node.
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*Node, error)
	// SetNodeAcl replaces the complete ACL of a node. Requires
	// PERMISSION_ACL_MANAGE on the node.
	SetNodeAcl(ctx context.Context, in *SetNodeAclRequest, opts ...grpc.CallOption) (*NodeAcl, error)
	// UnlockNode exchanges a folder password for a short-lived node token that
	// the client sends in the X-Node-Token header to reach the folder and its
	// descendants. The password must be RSA-OAEP(SHA-256) encrypted and base64
	// encoded, exactly like an account password.
	UnlockNode(ctx context.Context, in *UnlockNodeRequest, opts ...grpc.CallOption) (*NodeUnlock, error)
	// MoveNodes moves nodes to another folder in one transaction. The operation
	// is all-or-nothing: a single rejected node rolls the whole batch back.
	MoveNodes(ctx context.Context, in *MoveNodesRequest, opts ...grpc.CallOption) (*NodeSet, error)
	// CopyNodes copies nodes, including folder subtrees, into another folder.
	CopyNodes(ctx context.Context, in *CopyNodesRequest, opts ...grpc.CallOption) (*NodeSet, error)
	// DeleteNodes moves nodes to the trash. The rows and the stored objects are
	// retained until PurgeNodes or EmptyTrash. A deleted folder keeps its
	// contents, and ListTrash shows it as one entry instead of flattening the
	// subtree into the listing.
	DeleteNodes(ctx context.Context, in *DeleteNodesRequest, opts ...grpc.CallOption) (*DeleteNodesReply, error)
	// RestoreNodes restores nodes from the trash.
	RestoreNodes(ctx context.Context, in *RestoreNodesRequest, opts ...grpc.CallOption) (*NodeSet, error)
	// PurgeNodes permanently deletes nodes and their stored objects. Requires
	// PERMISSION_TRASH_MANAGE.
	PurgeNodes(ctx context.Context, in *PurgeNodesRequest, opts ...grpc.CallOption) (*PurgeNodesReply, error)
	// EmptyTrash purges every trashed node visible to the caller.
	EmptyTrash(ctx context.Context, in *EmptyTrashRequest, opts ...grpc.CallOption) (*PurgeNodesReply, error)
	// ListNodeVersions returns the content history of a file node.
	ListNodeVersions(ctx context.Context, in *ListNodeVersionsRequest, opts ...grpc.CallOption) (*NodeVersionSet, error)
	// RestoreNodeVersion promotes an older version to be the current content.
	RestoreNodeVersion(ctx context.Context, in *RestoreNodeVersionRequest, opts ...grpc.CallOption) (*Node, error)
	// DeleteNodeVersion drops one version and reclaims its stored object.
	DeleteNodeVersion(ctx context.Context, in *DeleteNodeVersionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*NodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSet)
	err := c.cc.Invoke(ctx, NodeService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*NodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSet)
	err := c.cc.Invoke(ctx, NodeService_SearchNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodeTree(ctx context.Context, in *GetNodeTreeRequest, opts ...grpc.CallOption) (*NodeTree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTree)
	err := c.cc.Invoke(ctx, NodeService_GetNodeTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*NodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSet)
	err := c.cc.Invoke(ctx, NodeService_ListTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, NodeService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodePath(ctx context.Context, in *GetNodePathRequest, opts ...grpc.CallOption) (*NodePath, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePath)
	err := c.cc.Invoke(ctx, NodeService_GetNodePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodeStats(ctx context.Context, in *GetNodeStatsRequest, opts ...grpc.CallOption) (*NodeStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStats)
	err := c.cc.Invoke(ctx, NodeService_GetNodeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodeAcl(ctx context.Context, in *GetNodeAclRequest, opts ...grpc.CallOption) (*NodeAcl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeAcl)
	err := c.cc.Invoke(ctx, NodeService_GetNodeAcl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, NodeService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, NodeService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetNodeAcl(ctx context.Context, in *SetNodeAclRequest, opts ...grpc.CallOption) (*NodeAcl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeAcl)
	err := c.cc.Invoke(ctx, NodeService_SetNodeAcl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UnlockNode(ctx context.Context, in *UnlockNodeRequest, opts ...grpc.CallOption) (*NodeUnlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeUnlock)
	err := c.cc.Invoke(ctx, NodeService_UnlockNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) MoveNodes(ctx context.Context, in *MoveNodesRequest, opts ...grpc.CallOption) (*NodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSet)
	err := c.cc.Invoke(ctx, NodeService_MoveNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CopyNodes(ctx context.Context, in *CopyNodesRequest, opts ...grpc.CallOption) (*NodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSet)
	err := c.cc.Invoke(ctx, NodeService_CopyNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteNodes(ctx context.Context, in *DeleteNodesRequest, opts ...grpc.CallOption) (*DeleteNodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodesReply)
	err := c.cc.Invoke(ctx, NodeService_DeleteNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestoreNodes(ctx context.Context, in *RestoreNodesRequest, opts ...grpc.CallOption) (*NodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSet)
	err := c.cc.Invoke(ctx, NodeService_RestoreNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) PurgeNodes(ctx context.Context, in *PurgeNodesRequest, opts ...grpc.CallOption) (*PurgeNodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeNodesReply)
	err := c.cc.Invoke(ctx, NodeService_PurgeNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) EmptyTrash(ctx context.Context, in *EmptyTrashRequest, opts ...grpc.CallOption) (*PurgeNodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeNodesReply)
	err := c.cc.Invoke(ctx, NodeService_EmptyTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListNodeVersions(ctx context.Context, in *ListNodeVersionsRequest, opts ...grpc.CallOption) (*NodeVersionSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeVersionSet)
	err := c.cc.Invoke(ctx, NodeService_ListNodeVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestoreNodeVersion(ctx context.Context, in *RestoreNodeVersionRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, NodeService_RestoreNodeVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteNodeVersion(ctx context.Context, in *DeleteNodeVersionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeService_DeleteNodeVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService manages the file tree. Folders are modelled as nodes of kind
// NODE_KIND_FOLDER, so description, ACL, visibility and password protection
// apply to files and folders alike.
//
// Access to a node is decided in this order:
//  1. the caller must hold PERMISSION_VIEW (or the permission matching the
//     operation) in its account permission set;
//  2. the owner of a node always holds every permission on it;
//  3. an explicit DENY entry on the node or any ancestor wins immediately;
//  4. an explicit ALLOW entry on the node or an inheriting ancestor grants
//     the permission;
//  5. VISIBILITY_PUBLIC grants read access to anybody, VISIBILITY_INTERNAL
//     grants read access to any authenticated caller, VISIBILITY_PRIVATE
//     grants nothing beyond the rules above.
//  6. a password protected folder additionally requires a node unlock token
//     obtained from UnlockNode, sent in the X-Node-Token header.
type NodeServiceServer interface {
	// ListNodes returns the children of a folder, or the root listing when
	// parent_id is empty. Set recursive to walk the whole subtree.
	ListNodes(context.Context, *ListNodesRequest) (*NodeSet, error)
	// SearchNodes performs a tree-wide search over names and descriptions.
	SearchNodes(context.Context, *SearchNodesRequest) (*NodeSet, error)
	// GetNodeTree returns a folder subtree expanded to the requested depth in a
	// single round trip.
	GetNodeTree(context.Context, *GetNodeTreeRequest) (*NodeTree, error)
	// ListTrash returns the trashed nodes visible to the caller. Entries are
	// listed one level at a time, so a deleted folder shows up without its
	// contents: the top entry of every trashed subtree comes first, and
	// original_parent_id walks into one of those folders.
	ListTrash(context.Context, *ListTrashRequest) (*NodeSet, error)
	// GetNode returns a single node by id.
	GetNode(context.Context, *GetNodeRequest) (*Node, error)
	// GetNodePath returns the breadcrumb from the root to the node.
	GetNodePath(context.Context, *GetNodePathRequest) (*NodePath, error)
	// GetNodeStats returns aggregate counters for the node subtree.
	GetNodeStats(context.Context, *GetNodeStatsRequest) (*NodeStats, error)
	// GetNodeAcl returns the ACL entries attached to a node together with the
	// entries inherited from ancestors and the caller's effective permissions.
	GetNodeAcl(context.Context, *GetNodeAclRequest) (*NodeAcl, error)
	// CreateFolder creates a folder. The folder may carry a description, a
	// visibility, a password and, through SetNodeAcl, an allow/deny list.
	CreateFolder(context.Context, *CreateFolderRequest) (*Node, error)
	// UpdateNode applies a partial update to a node. Supported paths: `name`,
	// `description`, `visibility`, `metadata`, `password`, `remove_password`,
	// `parent_id`. Renaming or moving requires PERMISSION_EDIT on the node.
	UpdateNode(context.Context, *UpdateNodeRequest) (*Node, error)
	// SetNodeAcl replaces the complete ACL of a node. Requires
	// PERMISSION_ACL_MANAGE on the node.
	SetNodeAcl(context.Context, *SetNodeAclRequest) (*NodeAcl, error)
	// UnlockNode exchanges a folder password for a short-lived node token that
	// the client sends in the X-Node-Token header to reach the folder and its
	// descendants. The password must be RSA-OAEP(SHA-256) encrypted and base64
	// encoded, exactly like an account password.
	UnlockNode(context.Context, *UnlockNodeRequest) (*NodeUnlock, error)
	// MoveNodes moves nodes to another folder in one transaction. The operation
	// is all-or-nothing: a single rejected node rolls the whole batch back.
	MoveNodes(context.Context, *MoveNodesRequest) (*NodeSet, error)
	// CopyNodes copies nodes, including folder subtrees, into another folder.
	CopyNodes(context.Context, *CopyNodesRequest) (*NodeSet, error)
	// DeleteNodes moves nodes to the trash. The rows and the stored objects are
	// retained until PurgeNodes or EmptyTrash. A deleted folder keeps its
	// contents, and ListTrash shows it as one entry instead of flattening the
	// subtree into the listing.
	DeleteNodes(context.Context, *DeleteNodesRequest) (*DeleteNodesReply, error)
	// RestoreNodes restores nodes from the trash.
	RestoreNodes(context.Context, *RestoreNodesRequest) (*NodeSet, error)
	// PurgeNodes permanently deletes nodes and their stored objects. Requires
	// PERMISSION_TRASH_MANAGE.
	PurgeNodes(context.Context, *PurgeNodesRequest) (*PurgeNodesReply, error)
	// EmptyTrash purges every trashed node visible to the caller.
	EmptyTrash(context.Context, *EmptyTrashRequest) (*PurgeNodesReply, error)
	// ListNodeVersions returns the content history of a file node.
	ListNodeVersions(context.Context, *ListNodeVersionsRequest) (*NodeVersionSet, error)
	// RestoreNodeVersion promotes an older version to be the current content.
	RestoreNodeVersion(context.Context, *RestoreNodeVersionRequest) (*Node, error)
	// DeleteNodeVersion drops one version and reclaims its stored object.
	DeleteNodeVersion(context.Context, *DeleteNodeVersionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) ListNodes(context.Context, *ListNodesRequest) (*NodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedNodeServiceServer) SearchNodes(context.Context, *SearchNodesRequest) (*NodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchNodes not implemented")
}
func (UnimplementedNodeServiceServer) GetNodeTree(context.Context, *GetNodeTreeRequest) (*NodeTree, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeTree not implemented")
}
func (UnimplementedNodeServiceServer) ListTrash(context.Context, *ListTrashRequest) (*NodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrash not implemented")
}
func (UnimplementedNodeServiceServer) GetNode(context.Context, *GetNodeRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNodeServiceServer) GetNodePath(context.Context, *GetNodePathRequest) (*NodePath, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodePath not implemented")
}
func (UnimplementedNodeServiceServer) GetNodeStats(context.Context, *GetNodeStatsRequest) (*NodeStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStats not implemented")
}
func (UnimplementedNodeServiceServer) GetNodeAcl(context.Context, *GetNodeAclRequest) (*NodeAcl, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeAcl not implemented")
}
func (UnimplementedNodeServiceServer) CreateFolder(context.Context, *CreateFolderRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedNodeServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedNodeServiceServer) SetNodeAcl(context.Context, *SetNodeAclRequest) (*NodeAcl, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNodeAcl not implemented")
}
func (UnimplementedNodeServiceServer) UnlockNode(context.Context, *UnlockNodeRequest) (*NodeUnlock, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockNode not implemented")
}
func (UnimplementedNodeServiceServer) MoveNodes(context.Context, *MoveNodesRequest) (*NodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveNodes not implemented")
}
func (UnimplementedNodeServiceServer) CopyNodes(context.Context, *CopyNodesRequest) (*NodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyNodes not implemented")
}
func (UnimplementedNodeServiceServer) DeleteNodes(context.Context, *DeleteNodesRequest) (*DeleteNodesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNodes not implemented")
}
func (UnimplementedNodeServiceServer) RestoreNodes(context.Context, *RestoreNodesRequest) (*NodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreNodes not implemented")
}
func (UnimplementedNodeServiceServer) PurgeNodes(context.Context, *PurgeNodesRequest) (*PurgeNodesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeNodes not implemented")
}
func (UnimplementedNodeServiceServer) EmptyTrash(context.Context, *EmptyTrashRequest) (*PurgeNodesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EmptyTrash not implemented")
}
func (UnimplementedNodeServiceServer) ListNodeVersions(context.Context, *ListNodeVersionsRequest) (*NodeVersionSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodeVersions not implemented")
}
func (UnimplementedNodeServiceServer) RestoreNodeVersion(context.Context, *RestoreNodeVersionRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreNodeVersion not implemented")
}
func (UnimplementedNodeServiceServer) DeleteNodeVersion(context.Context, *DeleteNodeVersionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNodeVersion not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SearchNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SearchNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SearchNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SearchNodes(ctx, req.(*SearchNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodeTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeTree(ctx, req.(*GetNodeTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListTrash(ctx, req.(*ListTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodePath(ctx, req.(*GetNodePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeStats(ctx, req.(*GetNodeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodeAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeAcl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeAcl(ctx, req.(*GetNodeAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetNodeAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetNodeAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetNodeAcl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetNodeAcl(ctx, req.(*SetNodeAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UnlockNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UnlockNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_UnlockNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UnlockNode(ctx, req.(*UnlockNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_MoveNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).MoveNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_MoveNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).MoveNodes(ctx, req.(*MoveNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CopyNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CopyNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CopyNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CopyNodes(ctx, req.(*CopyNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteNodes(ctx, req.(*DeleteNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestoreNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestoreNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestoreNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestoreNodes(ctx, req.(*RestoreNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_PurgeNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).PurgeNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_PurgeNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).PurgeNodes(ctx, req.(*PurgeNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_EmptyTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).EmptyTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_EmptyTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).EmptyTrash(ctx, req.(*EmptyTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListNodeVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListNodeVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListNodeVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListNodeVersions(ctx, req.(*ListNodeVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestoreNodeVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreNodeVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestoreNodeVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestoreNodeVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestoreNodeVersion(ctx, req.(*RestoreNodeVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteNodeVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteNodeVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteNodeVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteNodeVersion(ctx, req.(*DeleteNodeVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netdisk.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _NodeService_ListNodes_Handler,
		},
		{
			MethodName: "SearchNodes",
			Handler:    _NodeService_SearchNodes_Handler,
		},
		{
			MethodName: "GetNodeTree",
			Handler:    _NodeService_GetNodeTree_Handler,
		},
		{
			MethodName: "ListTrash",
			Handler:    _NodeService_ListTrash_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NodeService_GetNode_Handler,
		},
		{
			MethodName: "GetNodePath",
			Handler:    _NodeService_GetNodePath_Handler,
		},
		{
			MethodName: "GetNodeStats",
			Handler:    _NodeService_GetNodeStats_Handler,
		},
		{
			MethodName: "GetNodeAcl",
			Handler:    _NodeService_GetNodeAcl_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _NodeService_CreateFolder_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _NodeService_UpdateNode_Handler,
		},
		{
			MethodName: "SetNodeAcl",
			Handler:    _NodeService_SetNodeAcl_Handler,
		},
		{
			MethodName: "UnlockNode",
			Handler:    _NodeService_UnlockNode_Handler,
		},
		{
			MethodName: "MoveNodes",
			Handler:    _NodeService_MoveNodes_Handler,
		},
		{
			MethodName: "CopyNodes",
			Handler:    _NodeService_CopyNodes_Handler,
		},
		{
			MethodName: "DeleteNodes",
			Handler:    _NodeService_DeleteNodes_Handler,
		},
		{
			MethodName: "RestoreNodes",
			Handler:    _NodeService_RestoreNodes_Handler,
		},
		{
			MethodName: "PurgeNodes",
			Handler:    _NodeService_PurgeNodes_Handler,
		},
		{
			MethodName: "EmptyTrash",
			Handler:    _NodeService_EmptyTrash_Handler,
		},
		{
			MethodName: "ListNodeVersions",
			Handler:    _NodeService_ListNodeVersions_Handler,
		},
		{
			MethodName: "RestoreNodeVersion",
			Handler:    _NodeService_RestoreNodeVersion_Handler,
		},
		{
			MethodName: "DeleteNodeVersion",
			Handler:    _NodeService_DeleteNodeVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netdisk/v1/node.proto",
}
