// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: netdisk/v1/system.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSystemServiceGetStorageStats = "/netdisk.v1.SystemService/GetStorageStats"
const OperationSystemServiceGetSystemInfo = "/netdisk.v1.SystemService/GetSystemInfo"
const OperationSystemServiceHealthCheck = "/netdisk.v1.SystemService/HealthCheck"
const OperationSystemServiceListSystemSettings = "/netdisk.v1.SystemService/ListSystemSettings"
const OperationSystemServiceRunMaintenance = "/netdisk.v1.SystemService/RunMaintenance"
const OperationSystemServiceUpdateSystemSettings = "/netdisk.v1.SystemService/UpdateSystemSettings"

type SystemServiceHTTPServer interface {
	// GetStorageStats GetStorageStats aggregates storage usage across accounts.
	GetStorageStats(context.Context, *GetStorageStatsRequest) (*StorageStats, error)
	// GetSystemInfo GetSystemInfo returns the capabilities, limits and public auth parameters
	// of this deployment. This endpoint is public.
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*SystemInfo, error)
	// HealthCheck HealthCheck reports whether the process can reach its dependencies. This
	// endpoint is public.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthStatus, error)
	// ListSystemSettings ListSystemSettings returns the runtime tunables that may be changed
	// without a restart.
	ListSystemSettings(context.Context, *ListSystemSettingsRequest) (*SystemSettingSet, error)
	// RunMaintenance RunMaintenance triggers the housekeeping jobs: expiring stale upload
	// sessions, releasing objects queued for deletion, reclaiming orphaned
	// objects, expiring share links and recounting per-account usage.
	RunMaintenance(context.Context, *RunMaintenanceRequest) (*MaintenanceReport, error)
	// UpdateSystemSettings UpdateSystemSettings writes runtime tunables. Values are validated against
	// the documented bounds of each key.
	UpdateSystemSettings(context.Context, *UpdateSystemSettingsRequest) (*SystemSettingSet, error)
}

func RegisterSystemServiceHTTPServer(s *http.Server, srv SystemServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/system/info", _SystemService_GetSystemInfo0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/health", _SystemService_HealthCheck0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/storage/stats", _SystemService_GetStorageStats0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/system/maintenance/run", _SystemService_RunMaintenance0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/settings/list", _SystemService_ListSystemSettings0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/system/settings/update", _SystemService_UpdateSystemSettings0_HTTP_Handler(srv))
}

func _SystemService_GetSystemInfo0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSystemInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSystemServiceGetSystemInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemInfo)
		return ctx.Result(200, reply)
	}
}

func _SystemService_HealthCheck0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSystemServiceHealthCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HealthCheck(ctx, req.(*HealthCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthStatus)
		return ctx.Result(200, reply)
	}
}

func _SystemService_GetStorageStats0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStorageStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSystemServiceGetStorageStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStorageStats(ctx, req.(*GetStorageStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StorageStats)
		return ctx.Result(200, reply)
	}
}

func _SystemService_RunMaintenance0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RunMaintenanceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSystemServiceRunMaintenance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RunMaintenance(ctx, req.(*RunMaintenanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MaintenanceReport)
		return ctx.Result(200, reply)
	}
}

func _SystemService_ListSystemSettings0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSystemSettingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSystemServiceListSystemSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSystemSettings(ctx, req.(*ListSystemSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemSettingSet)
		return ctx.Result(200, reply)
	}
}

func _SystemService_UpdateSystemSettings0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSystemSettingsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSystemServiceUpdateSystemSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSystemSettings(ctx, req.(*UpdateSystemSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemSettingSet)
		return ctx.Result(200, reply)
	}
}

type SystemServiceHTTPClient interface {
	// GetStorageStats GetStorageStats aggregates storage usage across accounts.
	GetStorageStats(ctx context.Context, req *GetStorageStatsRequest, opts ...http.CallOption) (rsp *StorageStats, err error)
	// GetSystemInfo GetSystemInfo returns the capabilities, limits and public auth parameters
	// of this deployment. This endpoint is public.
	GetSystemInfo(ctx context.Context, req *GetSystemInfoRequest, opts ...http.CallOption) (rsp *SystemInfo, err error)
	// HealthCheck HealthCheck reports whether the process can reach its dependencies. This
	// endpoint is public.
	HealthCheck(ctx context.Context, req *HealthCheckRequest, opts ...http.CallOption) (rsp *HealthStatus, err error)
	// ListSystemSettings ListSystemSettings returns the runtime tunables that may be changed
	// without a restart.
	ListSystemSettings(ctx context.Context, req *ListSystemSettingsRequest, opts ...http.CallOption) (rsp *SystemSettingSet, err error)
	// RunMaintenance RunMaintenance triggers the housekeeping jobs: expiring stale upload
	// sessions, releasing objects queued for deletion, reclaiming orphaned
	// objects, expiring share links and recounting per-account usage.
	RunMaintenance(ctx context.Context, req *RunMaintenanceRequest, opts ...http.CallOption) (rsp *MaintenanceReport, err error)
	// UpdateSystemSettings UpdateSystemSettings writes runtime tunables. Values are validated against
	// the documented bounds of each key.
	UpdateSystemSettings(ctx context.Context, req *UpdateSystemSettingsRequest, opts ...http.CallOption) (rsp *SystemSettingSet, err error)
}

type SystemServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSystemServiceHTTPClient(client *http.Client) SystemServiceHTTPClient {
	return &SystemServiceHTTPClientImpl{client}
}

// GetStorageStats GetStorageStats aggregates storage usage across accounts.
func (c *SystemServiceHTTPClientImpl) GetStorageStats(ctx context.Context, in *GetStorageStatsRequest, opts ...http.CallOption) (*StorageStats, error) {
	var out StorageStats
	pattern := "/v1/system/storage/stats"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSystemServiceGetStorageStats),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSystemInfo GetSystemInfo returns the capabilities, limits and public auth parameters
// of this deployment. This endpoint is public.
func (c *SystemServiceHTTPClientImpl) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...http.CallOption) (*SystemInfo, error) {
	var out SystemInfo
	pattern := "/v1/system/info"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSystemServiceGetSystemInfo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HealthCheck HealthCheck reports whether the process can reach its dependencies. This
// endpoint is public.
func (c *SystemServiceHTTPClientImpl) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...http.CallOption) (*HealthStatus, error) {
	var out HealthStatus
	pattern := "/v1/system/health"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSystemServiceHealthCheck),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSystemSettings ListSystemSettings returns the runtime tunables that may be changed
// without a restart.
func (c *SystemServiceHTTPClientImpl) ListSystemSettings(ctx context.Context, in *ListSystemSettingsRequest, opts ...http.CallOption) (*SystemSettingSet, error) {
	var out SystemSettingSet
	pattern := "/v1/system/settings/list"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSystemServiceListSystemSettings),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RunMaintenance RunMaintenance triggers the housekeeping jobs: expiring stale upload
// sessions, releasing objects queued for deletion, reclaiming orphaned
// objects, expiring share links and recounting per-account usage.
func (c *SystemServiceHTTPClientImpl) RunMaintenance(ctx context.Context, in *RunMaintenanceRequest, opts ...http.CallOption) (*MaintenanceReport, error) {
	var out MaintenanceReport
	pattern := "/v1/system/maintenance/run"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSystemServiceRunMaintenance),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSystemSettings UpdateSystemSettings writes runtime tunables. Values are validated against
// the documented bounds of each key.
func (c *SystemServiceHTTPClientImpl) UpdateSystemSettings(ctx context.Context, in *UpdateSystemSettingsRequest, opts ...http.CallOption) (*SystemSettingSet, error) {
	var out SystemSettingSet
	pattern := "/v1/system/settings/update"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSystemServiceUpdateSystemSettings),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
