// Code generated by ent, DO NOT EDIT.

package share

import (
	"nagisa/internal/biz"
	"nagisa/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUpdatedAt, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldToken, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldNodeID, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldOwnerID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldDescription, v))
}

// Permissions applies equality check predicate on the "permissions" field. It's identical to PermissionsEQ.
func Permissions(v biz.PermMask) predicate.Share {
	vc := int64(v)
	return predicate.Share(sql.FieldEQ(FieldPermissions, vc))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHint applies equality check predicate on the "password_hint" field. It's identical to PasswordHintEQ.
func PasswordHint(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPasswordHint, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// MaxDownloads applies equality check predicate on the "max_downloads" field. It's identical to MaxDownloadsEQ.
func MaxDownloads(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldMaxDownloads, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldDownloadCount, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldViewCount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v biz.ShareStatus) predicate.Share {
	vc := int32(v)
	return predicate.Share(sql.FieldEQ(FieldStatus, vc))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldUpdatedAt, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldToken, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldNodeID, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldOwnerID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldDescription, v))
}

// PermissionsEQ applies the EQ predicate on the "permissions" field.
func PermissionsEQ(v biz.PermMask) predicate.Share {
	vc := int64(v)
	return predicate.Share(sql.FieldEQ(FieldPermissions, vc))
}

// PermissionsNEQ applies the NEQ predicate on the "permissions" field.
func PermissionsNEQ(v biz.PermMask) predicate.Share {
	vc := int64(v)
	return predicate.Share(sql.FieldNEQ(FieldPermissions, vc))
}

// PermissionsIn applies the In predicate on the "permissions" field.
func PermissionsIn(vs ...biz.PermMask) predicate.Share {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.Share(sql.FieldIn(FieldPermissions, v...))
}

// PermissionsNotIn applies the NotIn predicate on the "permissions" field.
func PermissionsNotIn(vs ...biz.PermMask) predicate.Share {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.Share(sql.FieldNotIn(FieldPermissions, v...))
}

// PermissionsGT applies the GT predicate on the "permissions" field.
func PermissionsGT(v biz.PermMask) predicate.Share {
	vc := int64(v)
	return predicate.Share(sql.FieldGT(FieldPermissions, vc))
}

// PermissionsGTE applies the GTE predicate on the "permissions" field.
func PermissionsGTE(v biz.PermMask) predicate.Share {
	vc := int64(v)
	return predicate.Share(sql.FieldGTE(FieldPermissions, vc))
}

// PermissionsLT applies the LT predicate on the "permissions" field.
func PermissionsLT(v biz.PermMask) predicate.Share {
	vc := int64(v)
	return predicate.Share(sql.FieldLT(FieldPermissions, vc))
}

// PermissionsLTE applies the LTE predicate on the "permissions" field.
func PermissionsLTE(v biz.PermMask) predicate.Share {
	vc := int64(v)
	return predicate.Share(sql.FieldLTE(FieldPermissions, vc))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldPasswordHash, v))
}

// PasswordHintEQ applies the EQ predicate on the "password_hint" field.
func PasswordHintEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPasswordHint, v))
}

// PasswordHintNEQ applies the NEQ predicate on the "password_hint" field.
func PasswordHintNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldPasswordHint, v))
}

// PasswordHintIn applies the In predicate on the "password_hint" field.
func PasswordHintIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldPasswordHint, vs...))
}

// PasswordHintNotIn applies the NotIn predicate on the "password_hint" field.
func PasswordHintNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldPasswordHint, vs...))
}

// PasswordHintGT applies the GT predicate on the "password_hint" field.
func PasswordHintGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldPasswordHint, v))
}

// PasswordHintGTE applies the GTE predicate on the "password_hint" field.
func PasswordHintGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldPasswordHint, v))
}

// PasswordHintLT applies the LT predicate on the "password_hint" field.
func PasswordHintLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldPasswordHint, v))
}

// PasswordHintLTE applies the LTE predicate on the "password_hint" field.
func PasswordHintLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldPasswordHint, v))
}

// PasswordHintContains applies the Contains predicate on the "password_hint" field.
func PasswordHintContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldPasswordHint, v))
}

// PasswordHintHasPrefix applies the HasPrefix predicate on the "password_hint" field.
func PasswordHintHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldPasswordHint, v))
}

// PasswordHintHasSuffix applies the HasSuffix predicate on the "password_hint" field.
func PasswordHintHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldPasswordHint, v))
}

// PasswordHintEqualFold applies the EqualFold predicate on the "password_hint" field.
func PasswordHintEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldPasswordHint, v))
}

// PasswordHintContainsFold applies the ContainsFold predicate on the "password_hint" field.
func PasswordHintContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldPasswordHint, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldExpiresAt))
}

// MaxDownloadsEQ applies the EQ predicate on the "max_downloads" field.
func MaxDownloadsEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldMaxDownloads, v))
}

// MaxDownloadsNEQ applies the NEQ predicate on the "max_downloads" field.
func MaxDownloadsNEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldMaxDownloads, v))
}

// MaxDownloadsIn applies the In predicate on the "max_downloads" field.
func MaxDownloadsIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldMaxDownloads, vs...))
}

// MaxDownloadsNotIn applies the NotIn predicate on the "max_downloads" field.
func MaxDownloadsNotIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldMaxDownloads, vs...))
}

// MaxDownloadsGT applies the GT predicate on the "max_downloads" field.
func MaxDownloadsGT(v int64) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldMaxDownloads, v))
}

// MaxDownloadsGTE applies the GTE predicate on the "max_downloads" field.
func MaxDownloadsGTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldMaxDownloads, v))
}

// MaxDownloadsLT applies the LT predicate on the "max_downloads" field.
func MaxDownloadsLT(v int64) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldMaxDownloads, v))
}

// MaxDownloadsLTE applies the LTE predicate on the "max_downloads" field.
func MaxDownloadsLTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldMaxDownloads, v))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int64) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int64) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldDownloadCount, v))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v int64) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v int64) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldViewCount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v biz.ShareStatus) predicate.Share {
	vc := int32(v)
	return predicate.Share(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v biz.ShareStatus) predicate.Share {
	vc := int32(v)
	return predicate.Share(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...biz.ShareStatus) predicate.Share {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int32(vs[i])
	}
	return predicate.Share(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...biz.ShareStatus) predicate.Share {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int32(vs[i])
	}
	return predicate.Share(sql.FieldNotIn(FieldStatus, v...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v biz.ShareStatus) predicate.Share {
	vc := int32(v)
	return predicate.Share(sql.FieldGT(FieldStatus, vc))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v biz.ShareStatus) predicate.Share {
	vc := int32(v)
	return predicate.Share(sql.FieldGTE(FieldStatus, vc))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v biz.ShareStatus) predicate.Share {
	vc := int32(v)
	return predicate.Share(sql.FieldLT(FieldStatus, vc))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v biz.ShareStatus) predicate.Share {
	vc := int32(v)
	return predicate.Share(sql.FieldLTE(FieldStatus, vc))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Share) predicate.Share {
	return predicate.Share(sql.NotPredicates(p))
}
