// Command openapi enriches the gnostic generated document with the pieces it
// cannot express: the service description, the servers, the security schemes
// that authorise each operation, the shared error responses and the raw
// binary bindings that live outside the proto JSON codec.
//
// It is idempotent, so it can run after every `make api`, and it emits the
// document as YAML and as JSON together with a Swagger UI page that loads it.
//
//	go run ./tools/openapi -in openapi.yaml -out docs
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	in := flag.String("in", "openapi.yaml", "generated OpenAPI document to enrich")
	out := flag.String("out", "docs", "directory that receives the published copies")
	flag.Parse()

	doc, err := load(*in)
	if err != nil {
		log.Fatalf("openapi: %v", err)
	}
	root := doc.Content[0]

	enrich(root)
	addErrorSchema(root)
	addRawBindings(root)
	addErrorResponses(root)

	if err := writeYAML(*in, doc); err != nil {
		log.Fatalf("openapi: %v", err)
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		log.Fatalf("openapi: %v", err)
	}
	for _, name := range []string{"openapi.yaml", "swagger.yaml"} {
		if err := writeYAML(filepath.Join(*out, name), doc); err != nil {
			log.Fatalf("openapi: %v", err)
		}
	}
	if err := writeJSON(filepath.Join(*out, "openapi.json"), root); err != nil {
		log.Fatalf("openapi: %v", err)
	}
	if err := os.WriteFile(filepath.Join(*out, "index.html"), []byte(swaggerPage), 0o644); err != nil {
		log.Fatalf("openapi: %v", err)
	}
	fmt.Printf("openapi: wrote %s and %s/{openapi.yaml,swagger.yaml,openapi.json,index.html}\n", *in, *out)
}

func load(path string) (*yaml.Node, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if strings.Contains(string(raw), enrichmentMarker) {
		return nil, fmt.Errorf("%s is already enriched; run `make api` first so the document is regenerated from the proto files", path)
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return nil, fmt.Errorf("%s is not a YAML document", path)
	}
	return &doc, nil
}

// enrichmentMarker is written into the header of the published document so a
// second run without a regeneration is refused instead of compounding.
const enrichmentMarker = "then enriched by tools/openapi"

func writeYAML(path string, doc *yaml.Node) error {
	var buf strings.Builder
	buf.WriteString("# Generated by protoc-gen-openapi, then enriched by tools/openapi.\n")
	buf.WriteString("# Do not edit by hand: run `make api && make docs` instead.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc.Content[0]); err != nil {
		return fmt.Errorf("encode %s: %w", path, err)
	}
	if err := enc.Close(); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(buf.String()), 0o644)
}

func writeJSON(path string, root *yaml.Node) error {
	raw, err := yaml.Marshal(root)
	if err != nil {
		return fmt.Errorf("re-encode for json: %w", err)
	}
	var plain any
	if err := yaml.Unmarshal(raw, &plain); err != nil {
		return fmt.Errorf("decode for json: %w", err)
	}
	out, err := json.MarshalIndent(normalise(plain), "", "  ")
	if err != nil {
		return fmt.Errorf("encode json: %w", err)
	}
	return os.WriteFile(path, append(out, '\n'), 0o644)
}

// normalise turns the YAML decoded value into something encoding/json accepts,
// where every map key has to be a string.
func normalise(value any) any {
	switch v := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(v))
		for key, item := range v {
			out[key] = normalise(item)
		}
		return out
	case map[any]any:
		out := make(map[string]any, len(v))
		for key, item := range v {
			out[fmt.Sprint(key)] = normalise(item)
		}
		return out
	case []any:
		out := make([]any, len(v))
		for i, item := range v {
			out[i] = normalise(item)
		}
		return out
	default:
		return value
	}
}

// enrich adds the document level metadata, the security schemes and the
// per-operation security requirement.
func enrich(root *yaml.Node) {
	info := mapLookup(root, "info")
	if info == nil {
		info = mapNode()
		mapSet(root, "info", info)
	}
	mapSet(info, "title", str("Nagisa 网盘 API"))
	mapSet(info, "version", str("1.0.0"))
	mapSet(info, "description", literal(apiDescription))
	mapSet(info, "contact", mapNode(
		str("name"), str("Nagisa Netdisk"),
	))
	mapSet(info, "license", mapNode(str("name"), str("MIT")))

	mapSet(root, "servers", seq(
		mapNode(str("url"), str("http://127.0.0.1:8000"), str("description"), str("本地开发环境")),
	))

	mapSet(root, "tags", seq(
		mapNode(str("name"), str("AuthService"), str("description"), str("账号认证与会话管理：登录、刷新、退出、修改密码。除 GetAuthConfig 与 Login 外均需访问令牌。")),
		mapNode(str("name"), str("UserService"), str("description"), str("账号管理：仅持有 user_manage 权限且等级严格高于目标的账号可以创建、修改、禁用、删除账号并分配权限。")),
		mapNode(str("name"), str("NodeService"), str("description"), str("文件树：文件夹与文件统一为节点，共用描述、可见范围、访问名单与密码模型。")),
		mapNode(str("name"), str("FileService"), str("description"), str("内容传输：分片上传、签名下载地址、预览与打包下载。")),
		mapNode(str("name"), str("ShareService"), str("description"), str("分享链接：把节点以独立的能力集合发布给没有账号的访问者。AccessShare、ListShareChildren、GetShareDownloadUrl 为匿名接口。")),
		mapNode(str("name"), str("AuditService"), str("description"), str("审计日志：记录每一次状态变更及其结果，只增不改。")),
		mapNode(str("name"), str("SystemService"), str("description"), str("系统信息、存储统计、运行参数与维护任务。GetSystemInfo 与 HealthCheck 为匿名接口。")),
	))

	components := mapLookup(root, "components")
	if components == nil {
		components = mapNode()
		mapSet(root, "components", components)
	}
	mapSet(components, "securitySchemes", mapNode(
		str("bearerAuth"), mapNode(
			str("type"), str("http"),
			str("scheme"), str("bearer"),
			str("bearerFormat"), str("JWT"),
			str("description"), literal("访问令牌。先调用 AuthService.Login 取得 accessToken，再以 `Authorization: Bearer <token>` 发送。"),
		),
		str("nodeToken"), mapNode(
			str("type"), str("apiKey"),
			str("in"), str("header"),
			str("name"), str("X-Node-Token"),
			str("description"), literal("文件夹解锁令牌，由 NodeService.UnlockNode 返回。访问受密码保护的文件夹及其子节点时必须携带。"),
		),
		str("shareToken"), mapNode(
			str("type"), str("apiKey"),
			str("in"), str("header"),
			str("name"), str("X-Share-Token"),
			str("description"), literal("分享访问令牌，由 ShareService.AccessShare 返回，用于访问设有密码的分享链接。"),
		),
		str("requestId"), mapNode(
			str("type"), str("apiKey"),
			str("in"), str("header"),
			str("name"), str("X-Request-Id"),
			str("description"), literal("可选。调用方自带的链路标识，会写入审计日志并原样回显。"),
		),
	))

	mapSet(root, "security", seq(mapNode(str("bearerAuth"), seq())))

	// Anonymous endpoints must not advertise a bearer requirement, otherwise a
	// generated client would refuse to call them.
	paths := mapLookup(root, "paths")
	if paths == nil {
		return
	}
	for i := 0; i+1 < len(paths.Content); i += 2 {
		operations := paths.Content[i+1]
		for j := 0; j+1 < len(operations.Content); j += 2 {
			op := operations.Content[j+1]
			id := ""
			if node := mapLookup(op, "operationId"); node != nil {
				id = node.Value
			}
			if _, public := publicOperations[id]; public {
				mapSet(op, "security", seq())
				if desc := mapLookup(op, "description"); desc != nil {
					desc.Value = desc.Value + "\n\n本接口为公开接口，无需访问令牌。"
				}
			}
		}
	}
}

// addErrorSchema publishes the error envelope and the reason enumeration. The
// envelope is produced by the server's error encoder rather than by a proto
// message, so the generator cannot know about it.
func addErrorSchema(root *yaml.Node) {
	components := mapLookup(root, "components")
	schemas := mapLookup(components, "schemas")
	if schemas == nil {
		schemas = mapNode()
		mapSet(components, "schemas", schemas)
	}
	reasons := make([]*yaml.Node, 0, len(errorReasons))
	for _, reason := range errorReasons {
		reasons = append(reasons, str(reason))
	}
	mapSet(schemas, "netdisk.v1.Error", mapNode(
		str("type"), str("object"),
		str("description"), str("统一错误响应。reason 取自 ErrorReason 枚举，调用方应按其分支。"),
		str("required"), seq(str("code"), str("reason")),
		str("properties"), mapNode(
			str("code"), mapNode(str("type"), str("integer"), str("format"), str("int32"), str("description"), str("HTTP 状态码")),
			str("reason"), mapNode(str("type"), str("string"), str("description"), str("机器可读的错误原因"), str("enum"), seq(reasons...)),
			str("message"), mapNode(str("type"), str("string"), str("description"), str("人类可读的说明")),
			str("metadata"), mapNode(str("type"), str("object"), str("additionalProperties"), mapNode(str("type"), str("string")), str("description"), str("附加上下文")),
		),
	))
}

// errorReasons mirrors api/netdisk/v1/error_reason.proto.
var errorReasons = []string{
	"NETDISK_NOT_FOUND",
	"NETDISK_INVALID_ARGUMENT",
	"NETDISK_UNAUTHENTICATED",
	"NETDISK_PERMISSION_DENIED",
	"NETDISK_CONFLICT",
	"NETDISK_INTERNAL",
	"NETDISK_UNAVAILABLE",
	"NETDISK_QUOTA_EXCEEDED",
	"NETDISK_STORAGE_ERROR",
	"NETDISK_NODE_LOCKED",
	"NETDISK_NAME_CONFLICT",
	"NETDISK_CYCLE_DETECTED",
	"NETDISK_UPLOAD_INCOMPLETE",
	"NETDISK_UPLOAD_EXPIRED",
	"NETDISK_TOO_LARGE",
	"NETDISK_UNSUPPORTED",
	"NETDISK_RESOURCE_EXHAUSTED",
	"NETDISK_PRECONDITION_FAILED",
	"NETDISK_ALREADY_EXISTS",
	"NETDISK_ABORTED",
	"NETDISK_ACCOUNT_DISABLED",
}

// addRawBindings documents the binary endpoints that sit beside the generated
// routes. They cannot come from the proto file because they carry raw bytes
// rather than a JSON envelope.
func addRawBindings(root *yaml.Node) {
	paths := mapLookup(root, "paths")
	if paths == nil {
		return
	}
	raw := []*yaml.Node{
		keyed("/v1/files/{node_id}/content", mapNode(
			str("get"), mapNode(
				str("tags"), seq(str("FileService")),
				str("summary"), str("流式下载原文件（原始字节绑定）"),
				str("description"), literal("按 `GetDownloadUrl` 返回的签名地址下载原文件。支持 `Range` 请求头，因此可以断点续传；响应会带上 `Content-Disposition`、`ETag` 与 `Accept-Ranges`。\n\n授权完全由 URL 签名承担：`exp` 为过期时间戳，`sig` 为 HMAC 签名，`sub` 为发起者账号，`extra` 为 `inline` 或 `attachment`。签名绑定方法、路径、节点与过期时间，无法挪用到其它资源。"),
				str("operationId"), str("FileService_DownloadContent"),
				str("security"), seq(),
				str("parameters"), seq(
					pathParam("node_id", "文件节点 ID"),
					queryParam("exp", "签名过期时间（Unix 秒）", true),
					queryParam("sig", "签名值", true),
					queryParam("sub", "签名对应的账号 ID", false),
					queryParam("extra", "`inline` 表示内联展示，`attachment` 表示下载", false),
					headerParam("Range", "字节范围，例如 `bytes=0-1048575`", false),
				),
				str("responses"), mapNode(
					str("200"), mapNode(
						str("description"), str("文件内容"),
						str("content"), mapNode(str("application/octet-stream"), mapNode(str("schema"), mapNode(str("type"), str("string"), str("format"), str("binary")))),
					),
					str("206"), mapNode(str("description"), str("部分内容，与 `Range` 请求对应")),
					str("403"), respRef("Forbidden"),
					str("404"), respRef("NotFound"),
				),
			),
		)),
		keyed("/v1/files/{node_id}/archive", mapNode(
			str("get"), mapNode(
				str("tags"), seq(str("FileService")),
				str("summary"), str("打包下载文件夹（原始字节绑定）"),
				str("description"), literal("把文件夹整棵子树实时压缩为 zip 流式返回，不会在服务端产生临时对象；对单个文件节点则返回只含该文件的压缩包。\n\n签名由 `GetArchiveUrl` 签发，规则与内容下载一致，`extra` 为压缩包名称。"),
				str("operationId"), str("FileService_DownloadArchive"),
				str("security"), seq(),
				str("parameters"), seq(
					pathParam("node_id", "文件或文件夹节点 ID"),
					queryParam("exp", "签名过期时间（Unix 秒）", true),
					queryParam("sig", "签名值", true),
					queryParam("sub", "签名对应的账号 ID", false),
					queryParam("extra", "压缩包名称（不含扩展名）", false),
				),
				str("responses"), mapNode(
					str("200"), mapNode(
						str("description"), str("zip 压缩包"),
						str("content"), mapNode(str("application/zip"), mapNode(str("schema"), mapNode(str("type"), str("string"), str("format"), str("binary")))),
					),
					str("403"), respRef("Forbidden"),
					str("404"), respRef("NotFound"),
				),
			),
		)),
		keyed("/v1/files/uploads/{upload_id}/parts/{part_number}/raw", mapNode(
			str("put"), mapNode(
				str("tags"), seq(str("FileService")),
				str("summary"), str("以原始字节上传分片"),
				str("description"), literal("与 `FileService.UploadChunk` 等价，但请求体是原始字节而不是 base64 字符串，浏览器可以直接把文件切片 PUT 上来，省去约三分之一的传输开销。\n\n必须携带访问令牌，且只能是上传会话的拥有者或持有 storage_manage 权限的账号。Content-Length 必须与分片实际长度一致。"),
				str("operationId"), str("FileService_UploadChunkRaw"),
				str("parameters"), seq(
					pathParam("upload_id", "上传会话 ID"),
					pathParam("part_number", "分片序号，从 1 开始"),
				),
				str("requestBody"), mapNode(
					str("required"), boolean(true),
					str("content"), mapNode(str("application/octet-stream"), mapNode(str("schema"), mapNode(str("type"), str("string"), str("format"), str("binary")))),
				),
				str("responses"), mapNode(
					str("200"), mapNode(
						str("description"), str("分片已记录"),
						str("content"), mapNode(str("application/json"), mapNode(str("schema"), refSchema("netdisk.v1.UploadPart"))),
					),
					str("400"), respRef("BadRequest"),
					str("401"), respRef("Unauthenticated"),
					str("403"), respRef("Forbidden"),
					str("404"), respRef("NotFound"),
				),
			),
		)),
	}
	// Each entry is a key/value mapping node, so its pair is spliced into the
	// paths mapping rather than appended as a nested node.
	for _, entry := range raw {
		paths.Content = append(paths.Content, entry.Content...)
	}
}

// addErrorResponses attaches the shared error replies to every operation. The
// universal ones are always possible; the specific ones are derived from the
// error reasons the operation description names, so the document never claims
// a status an endpoint cannot produce.
func addErrorResponses(root *yaml.Node) {
	components := mapLookup(root, "components")
	responses := mapLookup(components, "responses")
	if responses == nil {
		responses = mapNode()
		mapSet(components, "responses", responses)
	}
	for _, r := range sharedResponses {
		mapSet(responses, r.name, r.node())
	}

	paths := mapLookup(root, "paths")
	for i := 0; i+1 < len(paths.Content); i += 2 {
		operations := paths.Content[i+1]
		for j := 0; j+1 < len(operations.Content); j += 2 {
			op := operations.Content[j+1]
			existing := mapLookup(op, "responses")
			if existing == nil {
				existing = mapNode()
				mapSet(op, "responses", existing)
			}
			description := ""
			if node := mapLookup(op, "description"); node != nil {
				description = node.Value
			}
			needed := map[string]bool{"401": true, "403": true, "500": true}
			id := ""
			if node := mapLookup(op, "operationId"); node != nil {
				id = node.Value
			}
			if _, public := publicOperations[id]; public {
				delete(needed, "401")
			}
			for reason, status := range reasonStatus {
				if strings.Contains(description, reason) {
					needed[status] = true
				}
			}
			// Walked in sorted order, not as a range over needed: map iteration
			// order would shuffle the shared error responses on every run, so
			// the published document would keep differing from itself.
			statuses := make([]string, 0, len(needed))
			for status := range needed {
				statuses = append(statuses, status)
			}
			sort.Strings(statuses)
			for _, status := range statuses {
				if mapLookup(existing, status) != nil {
					continue
				}
				ref, ok := errorResponses[status]
				if !ok {
					continue
				}
				mapSet(existing, status, respRef(ref))
			}
		}
	}
}

// publicOperations lists the operations that need no access token. It must
// stay in sync with internal/server/middleware/auth.go.
var publicOperations = map[string]struct{}{
	"AuthService_GetAuthConfig":        {},
	"AuthService_Login":                {},
	"AuthService_GuestLogin":           {},
	"AuthService_RefreshToken":         {},
	"ShareService_AccessShare":         {},
	"ShareService_ListShareChildren":   {},
	"ShareService_GetShareDownloadUrl": {},
	"SystemService_GetSystemInfo":      {},
	"SystemService_HealthCheck":        {},
}

// reasonStatus maps an error reason named in an operation description onto the
// HTTP status the server answers with.
var reasonStatus = map[string]string{
	"NOT_FOUND":           "404",
	"INVALID_ARGUMENT":    "400",
	"UNAUTHENTICATED":     "401",
	"PERMISSION_DENIED":   "403",
	"CONFLICT":            "409",
	"ALREADY_EXISTS":      "409",
	"NAME_CONFLICT":       "409",
	"QUOTA_EXCEEDED":      "403",
	"NODE_LOCKED":         "403",
	"ACCOUNT_DISABLED":    "403",
	"TOO_LARGE":           "413",
	"RESOURCE_EXHAUSTED":  "429",
	"UNAVAILABLE":         "503",
	"STORAGE_ERROR":       "500",
	"INTERNAL":            "500",
	"PRECONDITION_FAILED": "400",
	"UNSUPPORTED":         "400",
	"UPLOAD_INCOMPLETE":   "400",
	"UPLOAD_EXPIRED":      "400",
	"ABORTED":             "400",
	"CYCLE_DETECTED":      "400",
	"INVALID_ARGUMENTS":   "400",
}

// errorResponses maps an HTTP status onto the shared response component that
// documents it.
var errorResponses = map[string]string{
	"400": "BadRequest",
	"401": "Unauthenticated",
	"403": "Forbidden",
	"404": "NotFound",
	"409": "Conflict",
	"413": "TooLarge",
	"429": "ResourceExhausted",
	"500": "Internal",
	"503": "Unavailable",
}

type sharedResponse struct {
	name        string
	description string
}

var sharedResponses = []sharedResponse{
	{"BadRequest", "请求不合法或违反字段约束"},
	{"Unauthenticated", "缺少访问令牌，或令牌无效、已过期"},
	{"Forbidden", "已认证但缺少所需权限，或账号被禁用，或文件夹未解锁"},
	{"NotFound", "资源不存在或对调用方不可见"},
	{"Conflict", "与当前状态冲突，例如同名节点已存在"},
	{"TooLarge", "请求体或声明的大小超过配置上限"},
	{"ResourceExhausted", "触发限流或配额已用尽"},
	{"Internal", "服务端错误，详见审计日志与响应中的 reason"},
	{"Unavailable", "依赖不可用，例如对象存储或数据库"},
}

func (r sharedResponse) node() *yaml.Node {
	return mapNode(
		str("description"), str(r.description),
		str("content"), mapNode(
			str("application/json"), mapNode(
				str("schema"), refSchema("netdisk.v1.Error"),
			),
		),
	)
}

const apiDescription = `Nagisa 网盘后端 HTTP API。

## 认证
除下文列出的公开接口外，所有接口都需要在请求头携带 ` + "`Authorization: Bearer <accessToken>`" + `。
访问令牌由 ` + "`POST /v1/auth/login`" + ` 签发；调用前请先用 ` + "`GET /v1/auth/config`" + ` 取得 RSA 公钥，
把密码用 RSA-OAEP(SHA-256) 加密后 base64 编码再发送，服务端不会接受明文密码。
受密码保护的文件夹需要额外的 ` + "`X-Node-Token`" + ` 请求头，由 ` + "`POST /v1/nodes/{node_id}/unlock`" + ` 签发。

公开接口：` + "`AuthService.GetAuthConfig`、`AuthService.Login`、`AuthService.RefreshToken`、" +
	"`ShareService.AccessShare`、`ShareService.ListShareChildren`、`ShareService.GetShareDownloadUrl`、" +
	"`SystemService.GetSystemInfo`、`SystemService.HealthCheck`" + `。

## 数据传输格式
请求与响应使用 protobuf 的规范 JSON 映射：
枚举使用名称（如 ` + "`\"PERMISSION_UPLOAD\"`" + `），64 位整数使用字符串（如 ` + "`\"size\": \"1048576\"`" + `），
` + "`bytes`" + ` 字段使用 base64，` + "`google.protobuf.Timestamp`" + ` 使用 RFC 3339 字符串，
` + "`google.protobuf.FieldMask`" + ` 使用逗号分隔的 camelCase 路径字符串（如 ` + "`\"description,visibility\"`" + `）。
字段名同时接受 camelCase（文档中的写法）与原始下划线写法，便于调用方平滑迁移。

## 错误
失败响应统一为 ` + "`{\"code\":401,\"reason\":\"NETDISK_UNAUTHENTICATED\",\"message\":\"...\"}`" + `。
` + "`reason`" + ` 取自 ` + "`ErrorReason`" + ` 枚举，调用方应当按它分支，而不是解析 ` + "`message`" + `。

## 授权模型
账号等级（` + "`rank`" + `）构成严格的全序：默认管理员 1000、管理员 500、普通用户 100、访客 10。
调用方只能管理等级严格低于自己的账号，并且只能授予自己拥有的权限。
节点访问按「账号权限上限 → 属主通行 → 显式拒绝 → 显式允许（含继承）→ 可见范围 → 文件夹密码」的顺序判定，
详见 ` + "`docs/permissions.md`" + `。

## 原始字节绑定
` + "`GET /v1/files/{node_id}/content`、`GET /v1/files/{node_id}/archive`、" +
	"`PUT /v1/files/uploads/{upload_id}/parts/{part_number}/raw`" + ` 直接收发二进制内容，
授权由 URL 签名或访问令牌承担，详见各接口说明。
`

const swaggerPage = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nagisa 网盘 API</title>
<link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
<style>body{margin:0}#swagger-ui{min-height:100vh}</style>
</head>
<body>
<div id="swagger-ui"></div>
<script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js" crossorigin></script>
<script>
window.onload = function () {
  window.ui = SwaggerUIBundle({
    url: './openapi.yaml',
    dom_id: '#swagger-ui',
    deepLinking: true,
    displayRequestDuration: true,
    persistAuthorization: true,
    docExpansion: 'list',
    defaultModelsExpandDepth: 1,
    tryItOutEnabled: true
  });
};
</script>
<p style="font:14px system-ui;padding:16px 24px;color:#666">
  OpenAPI 文档：<a href="./openapi.yaml">openapi.yaml</a> ·
  <a href="./swagger.yaml">swagger.yaml</a> ·
  <a href="./openapi.json">openapi.json</a>
</p>
</body>
</html>
`

// --- small YAML node helpers -------------------------------------------------

func str(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}

func literal(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value, Style: yaml.LiteralStyle}
}

func boolean(value bool) *yaml.Node {
	v := "false"
	if value {
		v = "true"
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: v}
}

func seq(items ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq", Content: items}
}

func mapNode(pairs ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Content: pairs}
}

func keyed(key string, value *yaml.Node) *yaml.Node {
	return mapNode(str(key), value)
}

func mapLookup(node *yaml.Node, key string) *yaml.Node {
	if node == nil || node.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1]
		}
	}
	return nil
}

func mapSet(node *yaml.Node, key string, value *yaml.Node) {
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			node.Content[i+1] = value
			return
		}
	}
	node.Content = append(node.Content, str(key), value)
}

func refSchema(name string) *yaml.Node {
	return mapNode(str("$ref"), str("#/components/schemas/"+name))
}

func respRef(name string) *yaml.Node {
	return mapNode(str("$ref"), str("#/components/responses/"+name))
}

func pathParam(name, description string) *yaml.Node {
	return mapNode(
		str("name"), str(name),
		str("in"), str("path"),
		str("required"), boolean(true),
		str("description"), str(description),
		str("schema"), mapNode(str("type"), str("string")),
	)
}

func queryParam(name, description string, required bool) *yaml.Node {
	return mapNode(
		str("name"), str(name),
		str("in"), str("query"),
		str("required"), boolean(required),
		str("description"), str(description),
		str("schema"), mapNode(str("type"), str("string")),
	)
}

func headerParam(name, description string, required bool) *yaml.Node {
	return mapNode(
		str("name"), str(name),
		str("in"), str("header"),
		str("required"), boolean(required),
		str("description"), str(description),
		str("schema"), mapNode(str("type"), str("string")),
	)
}
